### ISSUE TITLE
TLS versions

### ISSUE THREAD

**Issue by tuimz** [metaregistrar/php-epp-client#101]
Hi,

I am getting an error `Error 2100: TLSv1 is no longer supported, please update to TLS1.2 or higher `

I have tried to increase the TLS version by setting `curl_setopt ($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);` in eppHttpsConnection.php but that didn't solve it.

Any ideas? We are using PHP5.6, cURL version 7.29.0

**Comment by metaregistrar** [comment]
With which registry do you get this error?

The code in eppHttpsConnection is only used for those registries that use EPP over HTTPS, where most registries have a direct EPP socket connection, no curl involved.

**Comment by tuimz** [comment]
I see, we are using SIDN. Connection is configured to `tls://drs.domain-registry.nl` port 700

**Comment by metaregistrar** [comment]
I have no problem connecting to SIDN, but i use ssl://drs.domain-registry.nl

**Comment by metaregistrar** [comment]
Have tried using tls://drs.domain-registry.nl and i get the same error, will try to fix this.

**Comment by tuimz** [comment]
It would be no problem for me to use ssl:// did you use port 443 in this case or?

**Comment by metaregistrar** [comment]
no, always port 700
