### ISSUE TITLE
2400 internal error

### ISSUE THREAD

**Issue by timmie01** [metaregistrar/php-epp-client#102]
Hi, by every request I get Error 2400, what I'm doing wrong?
I am trying checkdomain.php with SIDN. 

I ajdust checkdomain.php for sidn connection and I see the connection is working, I can also login, but the command domain:check fails with  error 2400

-----READ-----2017-08-15 21:55:15-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="1000">
      <msg>The transaction was completed successfully.</msg>
    </result>
    <trID>
      <clTRID>599351a2eea28</clTRID>
      <svTRID>04D5226D-BC57-4739-5148-9CF26A1DEA05</svTRID>
    </trID>
  </response>
</epp>
 
-----END-----2017-08-15 21:55:15-----
 
-----LOGIN-----2017-08-15 21:55:15-----
Logged in
-----END-----2017-08-15 21:55:15-----
 
-----WRITE-----2017-08-15 21:55:15-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
  <command>
    <check>
      <domain:check>
        <domain:name>nu.nl</domain:name>
      </domain:check>
    </check>
    <clTRID>599351a335e13</clTRID>
  </command>
</epp>
 
-----END-----2017-08-15 21:55:15-----
 
-----READ-----2017-08-15 21:55:15-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="2400">
      <msg>Internal error.</msg>
    </result>
    <trID>
      <clTRID>599351a335e13</clTRID>
      <svTRID>SIDN</svTRID>
    </trID>
  </response>
</epp>

**Comment by metaregistrar** [comment]
I presume there is something wrong with the XML formatting of the message but the XML on your message was not properly formatted. Please use the "insert code" option to show XML

**Comment by timmie01** [comment]
HI,


These is a XML formatting problem,

I deleted the namespace in the epp rule, and now I got an error back from SIDN that this is no binding for the namespace.


The correct format whould be


<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <command>
    <check>
      <domain:check
        xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
        <domain:name>dyris.nl</domain:name>
      </domain:check>
    </check>
    <clTRID>ABC-12345</clTRID>
  </command>
</epp>


The epp rule should look like

<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">

instead of

 <epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">


The domain:check rule shuold look like :

<domain:check
        xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">

instead of

<domain:check>


it look like the the xmlns:domain parameter is on the wrong rule.



This is the request/response from sidn if I delete the namespace from the epp rule


<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <command>
    <check>
      <domain:check>
        <domain:name>maastricht.nl</domain:name>
      </domain:check>
    </check>
    <clTRID>599413be457d8</clTRID>
  </command>
</epp>

-----END-----2017-08-16 11:43:26-----

-----READ-----2017-08-16 11:43:26-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="2001">
      <msg>Error at Line:0 Prefix [domain] used without binding it to a namespace URI</msg>
    </result>
    <trID>
      <clTRID>xxx</clTRID>
      <svTRID>SIDN</svTRID>
    </trID>
  </response>
</epp>



I don't now how to put the xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" in the domein:check rule dut I think this would be the solution.



________________________________

**Comment by metaregistrar** [comment]
SIDN accepts both ways, you can put the namespace directly into the first EPP line, or you can put it where it is used, in the domain check. 

There is a branch of php-epp-client that does just this, (branch namespaces-in-root-or-not), but you don't need to go there. The main branch php-epp-client should work fine with SIDN, as we use it daily for this.

Please find hereunder a correct example of how SIDN handles a domain:check using the standard php-epp-client library

`        ==== LOG ====`
`        -----CONNECT-----2017-08-16 12:21:32-----`
`        Connection made`
`        -----END-----2017-08-16 12:21:32-----`
`        -----WRITE-----2017-08-16 12:21:32-----`
`        <?xml version="1.0" encoding="UTF-8"?>`
`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">`
`    <command>`
`        <login>`
`            <clID>XXXXXXXXXXXXXXXX</clID>`
`            <pw>XXXXXXXXXXXXXXXX</pw>`
`            <options>`
`                <version>1.0</version>`
`                <lang>en</lang>`
`            </options>`
`            <svcs>`
`                <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>`
`                <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>`
`                <objURI>urn:ietf:params:xml:ns:host-1.0</objURI>`
`                <svcExtension>`
`                    <extURI>http://rxsd.domain-registry.nl/sidn-ext-epp-1.0</extURI>`
`                    <extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI>`
`                </svcExtension>`
`            </svcs>`
`        </login>`
`        <clTRID>59941cac2c7dd</clTRID>`
`    </command>`
`</epp>`
``
`        -----END-----2017-08-16 12:21:32-----`
``
`        -----READ-----2017-08-16 12:21:32-----`
`        <?xml version="1.0" encoding="UTF-8"?>`
`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">`
`<response>`
`    <result code="1000">`
`        <msg>The transaction was completed successfully.</msg>`
`    </result>`
`    <trID>`
`        <clTRID>59941cac2c7dd</clTRID>`
`        <svTRID>5508897A-0AF6-D1DD-5C79-5423E124C03B</svTRID>`
`    </trID>`
`</response>`
`</epp>`
``
`        -----END-----2017-08-16 12:21:32-----`
``
`        -----LOGIN-----2017-08-16 12:21:32-----`
`        Logged in`
`        -----END-----2017-08-16 12:21:32-----`
``
`        -----WRITE-----2017-08-16 12:21:32-----`
`        <?xml version="1.0" encoding="UTF-8"?>`
`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">`
`<command>`
`    <check>`
`        <domain:check>`
`            <domain:name>testen.nl</domain:name>`
`        </domain:check>`
`    </check>`
`    <clTRID>59941cac40888</clTRID>`
`</command>`
`</epp>`
``
`        -----END-----2017-08-16 12:21:32-----`
``
`        -----READ-----2017-08-16 12:21:32-----`
`        <?xml version="1.0" encoding="UTF-8"?>`
`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">`
`<response>`
`    <result code="1000">`
`        <msg>The availability of the domain name has been checked.</msg>`
`    </result>`
`    <resData>`
`        <domain:chkData>`
`            <domain:cd>`
`                <domain:name avail="true">testen.nl</domain:name>`
`            </domain:cd>`
`        </domain:chkData>`
`    </resData>`
`    <trID>`
`        <clTRID>59941cac40888</clTRID>`
`        <svTRID>2F77B2FE-880E-7AC2-2C6D-E728597BFB17</svTRID>`
`    </trID>`
`</response>`
`</epp>`
``
`        -----END-----2017-08-16 12:21:32-----`
``
`        -----WRITE-----2017-08-16 12:21:32-----`
`        <?xml version="1.0" encoding="UTF-8"?>`
`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">`
`<command>`
`    <logout></logout>`
`</command>`
`</epp>`
``
`        -----END-----2017-08-16 12:21:32-----`
``
`        -----READ-----2017-08-16 12:21:32-----`
`        <?xml version="1.0" encoding="UTF-8"?>`
`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">`
`<response>`
`    <result code="1500">`
`        <msg>You are now logged off.</msg>`
`    </result>`
`    <trID>`
`        <svTRID>59F0ADAC-11CE-EA64-A18F-60783129FB26</svTRID>`
`    </trID>`
`</response>`
`</epp>`
`        -----END-----2017-08-16 12:21:32-----`
`        -----LOGOUT-----2017-08-16 12:21:32-----`
`        Logged out`
`        -----END-----2017-08-16 12:21:32-----`
`        -----DISCONNECT-----2017-08-16 12:21:32-----`
`        Disconnected`
`        -----END-----2017-08-16 12:21:32-----`

**Comment by timmie01** [comment]
strange,


If I use the standard branch of php-epp-client  I get the same result see below.

Could it be a php problem, I use

PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies




-----WRITE-----2017-08-16 13:49:41-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0" xmlns:sidn-ext-epp="http://rxsd.domain-registry.nl/sidn-ext-epp-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1">
  <command>
    <check>
      <domain:check>
        <domain:name>maastricht.nl</domain:name>
      </domain:check>
    </check>
    <clTRID>59943155eca1e</clTRID>
  </command>
</epp>

-----END-----2017-08-16 13:49:41-----

-----READ-----2017-08-16 13:49:41-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="2400">
      <msg>Internal error.</msg>
    </result>
    <trID>
      <clTRID>59943155eca1e</clTRID>
      <svTRID>SIDN</svTRID>
    </trID>
  </response>
</epp>



________________________________

**Comment by metaregistrar** [comment]
Maybe you are nog logging in correctly. Please make sure that upon login this is included:

`<svcs>`
`<objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>`
`<objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>`
`<objURI>urn:ietf:params:xml:ns:host-1.0</objURI>`
`<svcExtension>`
`<extURI>http://rxsd.domain-registry.nl/sidn-ext-epp-1.0</extURI>`
`<extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI>`
`</svcExtension>`
`</svcs>`

**Comment by timmie01** [comment]
I am logged in successfully see log below.



==== LOG ====
-----CONNECT-----2017-08-16 15:39:34-----
Connection made
-----END-----2017-08-16 15:39:34-----

-----WRITE-----2017-08-16 15:39:34-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0" xmlns:sidn-ext-epp="http://rxsd.domain-registry.nl/sidn-ext-epp-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1">
  <command>
    <login>
      <clID>XXXXXXXXXXXXXXXX</clID>
      <pw>XXXXXXXXXXXXXXXX</pw>
      <options>
        <version>1.0</version>
        <lang>en</lang>
      </options>
      <svcs>
        <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>
        <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>
        <objURI>urn:ietf:params:xml:ns:host-1.0</objURI>
        <svcExtension>
          <extURI>http://rxsd.domain-registry.nl/sidn-ext-epp-1.0</extURI>
          <extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI>
        </svcExtension>
      </svcs>
    </login>
    <clTRID>59944b166cf71</clTRID>
  </command>
</epp>

-----END-----2017-08-16 15:39:34-----

-----READ-----2017-08-16 15:39:34-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="1000">
      <msg>The transaction was completed successfully.</msg>
    </result>
    <trID>
      <clTRID>59944b166cf71</clTRID>
      <svTRID>6CD9F25C-5B12-B3A5-C24F-A9FC5C4E5976</svTRID>
    </trID>
  </response>
</epp>

-----END-----2017-08-16 15:39:34-----

-----LOGIN-----2017-08-16 15:39:34-----
Logged in
-----END-----2017-08-16 15:39:34-----

-----WRITE-----2017-08-16 15:39:34-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0" xmlns:sidn-ext-epp="http://rxsd.domain-registry.nl/sidn-ext-epp-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1">
  <command>
    <check>
      <domain:check>
        <domain:name>maastricht.nl</domain:name>
      </domain:check>
    </check>
    <clTRID>59944b16a8abc</clTRID>
  </command>
</epp>

-----END-----2017-08-16 15:39:34-----

-----READ-----2017-08-16 15:39:34-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="2400">
      <msg>Internal error.</msg>
    </result>
    <trID>
      <clTRID>59944b16a8abc</clTRID>
      <svTRID>SIDN</svTRID>
    </trID>
  </response>
</epp>

-----END-----2017-08-16 15:39:34-----

-----WRITE-----2017-08-16 15:39:34-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0" xmlns:sidn-ext-epp="http://rxsd.domain-registry.nl/sidn-ext-epp-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1">
  <command>
    <logout></logout>
  </command>
</epp>

-----END-----2017-08-16 15:39:34-----

-----READ-----2017-08-16 15:39:34-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="1500">
      <msg>You are now logged off.</msg>
    </result>
    <trID>
      <svTRID>8991FFB8-77D5-53F3-5DB9-8C2AF1CCC510</svTRID>
    </trID>
  </response>
</epp>

-----END-----2017-08-16 15:39:34-----

-----LOGOUT-----2017-08-16 15:39:34-----
Logged out
-----END-----2017-08-16 15:39:34-----

-----DISCONNECT-----2017-08-16 15:39:34-----
Disconnected
-----END-----2017-08-16 15:39:34-----

________________________________

**Comment by metaregistrar** [comment]
Well, this surely is a nice riddle. I have done a 'diff' check of both our commands, and the only difference the system finds is the client transaction ID.

diff check2.xml check1.xml
9c9
<     <clTRID>59945328a768d</clTRID>
---
>     <clTRID>59944b16a8abc</clTRID>

Maybe you should send this off to support@sidn.nl and ask them what goes wrong. I am surely very curious what the answer is!

**Comment by timmie01** [comment]
Hello,


I just contact SIDN support, and there answer is that this error should be formatting error.

They unfortunately cannot see what is going wrong.


They ask me to use the example  xml for domaincheck  from there website, en try if then the error still exist, but I don't now how I can  use there xml.or ajust the xml that is an exact copy.


________________________________

**Comment by metaregistrar** [comment]
This sounds like a nice 'standard answer' from support. Are you using the live EPP service from SIDN or the test service?

**Comment by timmie01** [comment]
We use the live service on ssl://drs.domain-registry.nl on port 700



________________________________

**Comment by metaregistrar** [comment]
can you try if you have the same issue on SIDN test service? If you can tell them there is no issue on the test service with the same code, they will need to search deeper.

We have had this problem (error 2400) some time ago with SIDN, and they needed to restart a broken process to get it fixed.

**Comment by timmie01** [comment]
if I use the test service ( I only change the settings.ini file )  to ssl://testdrs.domain-registry.nl and use the test accounts then I get the following error ERROR: Error 2001: Error in login (clID and pw must be present).

The accounts are double check with sidn so they are working and in the XML I see the clID en pw.

So I seems there is a differents between test and production.


Checking 1 domain names
ERROR: Error 2001: Error in login (clID and pw must be present).

==== LOG ====
-----CONNECT-----2017-08-17 15:43:57-----
Connection made
-----END-----2017-08-17 15:43:57-----

-----WRITE-----2017-08-17 15:43:57-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0" xmlns:sidn-ext-epp="http://rxsd.domain-registry.nl/sidn-ext-epp-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1">
  <command>
    <login>
      <clID>XXXXXXXXXXXXXXXX</clID>
      <pw>XXXXXXXXXXXXXXXX</pw>
      <options>
        <version>1.0</version>
        <lang>en</lang>
      </options>
      <svcs>
        <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>
        <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>
        <objURI>urn:ietf:params:xml:ns:host-1.0</objURI>
        <svcExtension>
          <extURI>http://rxsd.domain-registry.nl/sidn-ext-epp-1.0</extURI>
          <extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI>
        </svcExtension>
      </svcs>
    </login>
    <clTRID>59959d9d4fec9</clTRID>
  </command>
</epp>

-----END-----2017-08-17 15:43:57-----

-----READ-----2017-08-17 15:43:57-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <response>
    <result code="2001">
      <msg>Error in login (clID and pw must be present).</msg>
    </result>
    <trID>
      <clTRID>59959d9d4fec9</clTRID>
      <svTRID>SIDN</svTRID>
    </trID>
  </response>
</epp>




________________________________

**Comment by metaregistrar** [comment]
Can you please pull the latest version from the repository - i have made an change where the system would put [<[CDATA]] around the password, but SIDN does not accept this. The latest version fixes this.

**Comment by timmie01** [comment]
I use the latest version, and now the test is wordking I can check the domain name in the test drs system.
Production give me an autorisatie error on the command check (error 2201)  but I see the connection is made and I am logged in. so now it is a different error as before and I will reset my EPP account password first, because I dit need to change my password  also 2 time before the test was working. I will change this tomorrow and let you know wat the result are.


On 17 Aug 2017, at 17:06, Ewout de Graaf <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please pull the latest version from the repository - i have made an change where the system would put [<[CDATA]] around the password, but SIDN does not accept this. The latest version fixes this.

**Comment by timmie01** [comment]
Hello Ewout,

Hereby an update on my problem.
After several contact with SIDN we finally have all working.
The problem was that our EPP account was active but wasn’t attach to a  role “deelnemer” within the EPP database, so it wasn’t a problem with the php program.
The attach me to this role and then everything was working as it should be..
SIDN will now go thru all there accounts so that the can adjust these if the not attached. The also make a note so that someone else have this problem the wil check this first.

Thank you for all your effort.


On 17 Aug 2017, at 17:06, Ewout de Graaf <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please pull the latest version from the repository - i have made an change where the system would put [<[CDATA]] around the password, but SIDN does not accept this. The latest version fixes this.

**Comment by metaregistrar** [comment]
Excellent, thanks. I also saw that SIDN corrected the [<[CATA]] issue with the password.
