### ISSUE TITLE
How can I choose/set the TLS Version

### ISSUE THREAD

**Issue by 4ld3v** [metaregistrar/php-epp-client#105]
Hi There

First off, thanks alot for the php-epp-client. 

We are using php-epp-client to communicate with the EPP Api of switch.ch. They have disabled everything older then TLS 1.2 on their end a couple of days ago. Now we are getting:

Error 2200: Authentication error

while trying to speak to the API.

I was trying to find out, where I could set the TLS Version to be used. I did try out in the settings.ini:
epp.nic.ch and tls://epp.nic.ch but I am still getting:

Error 2200: Authentication error

Is there another place I can specify the TLS version to be used?

Best Regards and Thanks
Ilir

**Comment by metaregistrar** [comment]
Have you already tried ssl://epp.nic.ch?

**Comment by 4ld3v** [comment]
Hi Ewout,

Thank you very much, yes I have tried ssl:// and it still fails. I contacted switch and they asked for some output of the requests i am sending. I found the debug boolean in your code, but when executing I still do only see the error message. How can I generate some debug output, so that I could see the payload being sent?

Thanks in Advance and Regard
Ilir

**Comment by metaregistrar** [comment]
Hi Llir,

Can you output the debug code for me? Please remove any userid's or passwords that might be in there.

**Comment by 4ld3v** [comment]
Thanks,

In the meantime, the root issue is solved, it seems that at switch our un/pw has been changed, still dont know how this happened. I had contacted switch even before opening this ticket and I was told then and today that the error I was receiving (Authentification Failure) was due to me not using TLS 1.2. But in the meantime just be sure I requested a new password and found out that the EPP username was neither correct anymore. This has been running for months and stopped working all of a sudden and just after they did disable TLS<1.2.

So thanks alot for the support and sorry for the noise. However, still the question as I couldnt find it out there, how do i run php-epp-client in debug mode, as the mentioned way i tried it didnt work, no debug output.

Regards
Ilir

**Comment by metaregistrar** [comment]
That is strange, no debug mode.

If you use the command Metaregistrar\EPP\eppConnection::create('configfile',true); 

This should create a constant echo of output to stdout();

The output only comes at the end, when all the processing is finished.

**Comment by 4ld3v** [comment]
Hi there

This way around it works and I get the debug output. 

Again, thank you for your help!

Regards
Ilir
