### ISSUE TITLE
how to additional the EPP <extension> option?

### ISSUE THREAD

**Issue by quyunet** [metaregistrar/php-epp-client#107]
EPP - fees Document: https://tools.ietf.org/html/draft-brown-epp-fees-06#page-14

example:
 <extension>
   <fee:trnData xmlns:fee="urn:ietf:params:xml:ns:fee-0.9">
   <fee:currency>USD</fee:currency>
   <fee:period unit="y">1</fee:period>
   <fee:fee>5.00</fee:fee>
   </fee:trnData>
</extension>

the .ws NIC must additional fees option.

**Comment by metaregistrar** [comment]
The fees extension is an important one, which we also will be using shortly. I wil start adding this extension on short notice.

**Comment by quyunet** [comment]
thnak you very much!

**Comment by quyunet** [comment]
hello, does this option provide a solution?
