### ISSUE TITLE
No valid response class found for request class Metaregistrar\EPP\ficoraEppCreateContactRequest

### ISSUE THREAD

**Issue by GVeidenberg** [metaregistrar/php-epp-client#108]
Hello

I have been struggling with this Ficora contact create and I am now in this point, where I get error
`No valid response class found for request class Metaregistrar\EPP\ficoraEppCreateContactRequest`

My createcontact.php looks like this :

`<?php
require('/var/www/html/EPPtest/autoloader.php');

use Metaregistrar\EPP\eppConnection;
use Metaregistrar\EPP\eppContactPostalInfo;
use Metaregistrar\EPP\eppContact;
use Metaregistrar\EPP\eppCreateContactRequest;
use Metaregistrar\EPP\eppException;
use Metaregistrar\EPP\eppCheckDomainRequest;
use Metaregistrar\EPP\eppCheckDomainResponse;
use Metaregistrar\EPP\eppDomain;
use Metaregistrar\EPP\eppHost;
use Metaregistrar\EPP\eppContactHandle;
use Metaregistrar\EPP\eppCheckContactRequest;
use Metaregistrar\EPP\eppCheckHostRequest;
use Metaregistrar\EPP\ficoraEppCreateContactRequest;
use Metaregistrar\EPP\eppCreateDomainRequest;
use Metaregistrar\EPP\eppCreateHostRequest;
use Metaregistrar\EPP\ficoraEppCheckBalanceRequest;
use Metaregistrar\EPP\ficoraEppCheckBalanceResponse;
use Metaregistrar\EPP\eppPollRequest;
use Metaregistrar\EPP\eppPollResponse;

/**
 * This code example creates a contact object with a registry
 */

try {
// Please enter your own settings file here under before using this example
    if ($conn = eppConnection::create('settings.ini')) {
        // Connect to the EPP server
        if ($conn->login()) {
            createcontact($conn, 'info@test.com', '+31.201234567', 'Domain Administration', 'Metaregistrar', 'Address 1', 'Zipcode', 'City', 'NL');
            $conn->logout();
        }
    }
} catch (eppException $e) {
    echo "ERROR: " . $e->getMessage() . "\n\n";
}

/**
 * @param $conn eppConnection
 * @param $email string
 * @param $telephone string
 * @param $name string
 * @param $organization string
 * @param $address string
 * @param $postcode string
 * @param $city string
 * @param $country string
 * @return null
 */
function createcontact($conn, $email, $telephone, $name, $organization, $address, $postcode, $city, $country) {
    /* @var $conn Metaregistrar\EPP\eppConnection */
    try {
        $contactinfo = new eppContact(new eppContactPostalInfo($name, $city, $country, $organization, $address, null, $postcode, eppContact::TYPE_LOC), $email, $telephone);
        // Ficora will not accept a password field in the request
        $contactinfo->setPassword(null);
        $contact = new ficoraEppCreateContactRequest($contactinfo);
        $contact->setRole(ficoraEppCreateContactRequest::FI_CONTACT_ROLE_TECHNICAL);
        $contact->setType(ficoraEppCreateContactRequest::FI_CONTACT_TYPE_COMPANY);
        $contact->setIsfinnish(false);
        $contact->setFirstname('Ewout');
        $contact->setLastname('de Graaf');
        $contact->setBirthdate('2005-04-03 22:00');
        $contact->setRegisternumber('1234312-5');
        $contact->setIdentity('123423A123F');
        $contact->setLegalemail($contactinfo->getEmail());
        if ($response = $conn->request($contact)) {
            /* @var $response Metaregistrar\EPP\eppCreateContactResponse */
            echo "Contact created on " . $response->getContactCreateDate() . " with id " . $response->getContactId() . "\n";
            return $response->getContactId();
        }
    } catch (eppException $e) {
        echo $e->getMessage() . "\n";
        echo $e->getLastCommand()."\n";
    }
    return null;
}`

Ficora eppConnection.php looks like this :
`<?php
namespace Metaregistrar\EPP;

class ficoraEppConnection extends eppConnection {

    public function __construct($logging = false, $settingsfile = null) {
        // Construct the EPP connection object en specify if you want logging on or off
        parent::__construct($logging, $settingsfile);
        
        // Specify timeout values in seconds, test interface is kind of slow
        parent::setTimeout(200);
        // Enable DNSSEC, Ficora supports this
        parent::enableDnssec();

        // Make sure services are not added to the main EPP commands
        parent::setServices(null);

        // Not a real extension, but okay then
        parent::addExtension('ficora','http://www.ficora.fi/epp/ficora');
        // Add the commands and responses specific to this registry
        // Please make sure the corresponding PHP files are present!
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppCreateContactRequest', 'Metaregistrar\EPP\eppCreateContactResponse');
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppCheckBalanceRequest', 'Metaregistrar\EPP\ficoraEppCheckBalanceResponse');
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppUpdateDomainRequest', 'Metaregistrar\EPP\eppUpdateDomainResponse');
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppInfoDomainRequest', 'Metaregistrar\EPP\ficoraEppInfoDomainResponse');
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppInfoContactRequest', 'Metaregistrar\EPP\ficoraEppInfoContactResponse');
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppUpdateContactRequest', 'Metaregistrar\EPP\eppUpdateContactResponse');
        parent::addCommandResponse('Metaregistrar\EPP\ficoraEppRenewRequest', 'Metaregistrar\EPP\eppRenewResponse');
    }

}`

Can anyone help`? Connection is working, etc.

**Comment by metaregistrar** [comment]
I have tried to revamp the way that extensions are added, also checked the ficora extension so that the additional function in this class are mapped properly.

Can you please try again with the latest version of php-epp-client?

**Comment by GVeidenberg** [comment]
Just downloaded. still get error with createcontact.php

No valid response class found for request class Metaregistrar\EPP\ficoraEppCreateContactRequest

If I use the original createcontact.php from Examples. The one you have in you script. I get errors:

 PHP Fatal error:  Uncaught Error: Call to undefined function Metaregistrar\EPP\mb_check_encoding() in /var/www/html/php-epp-client-master/Protocols/EPP/eppRequests/eppRequest.php:177
Stack trace:
#0 /var/www/html/php-epp-client-master/Protocols/EPP/eppRequests/eppCreateContactRequest.php(67): Metaregistrar\EPP\eppRequest::isAscii('Domain Administ...')
#1 /var/www/html/php-epp-client-master/Protocols/EPP/eppRequests/eppCreateContactRequest.php(39): Metaregistrar\EPP\eppCreateContactRequest->setPostalInfo(Object(Metaregistrar\EPP\eppContactPostalInfo))
#2 /var/www/html/php-epp-client-master/Protocols/EPP/eppRequests/eppCreateContactRequest.php(17): Metaregistrar\EPP\eppCreateContactRequest->setContact(Object(Metaregistrar\EPP\eppContact))
#3 /var/www/html/php-epp-client-master/Examples/createcontact.php(45): Metaregistrar\EPP\eppCreateContactRequest->__construct(Object(Metaregistrar\EPP\eppContact))
#4 /var/www/html/php-epp-client-master/Examples/createcontact.php(19): createcontact(Object(Metaregistrar\EPP\eppConnection), 'info in /var/www/html/php-epp-client-master/Protocols/EPP/eppRequests/eppRequest.php on line 177

**Comment by metaregistrar** [comment]
The function mb_check_encoding is in PHP since version 4.4.3, strange that you get this error.

You could change the lines 67-71 in eppCreateContactRequest.php yourself and set postal type to INT or LOC as the registry requires.

in Protocols/EPP/eppExtensions/ficora/includes.php you find this line: 
$this->addCommandResponse('Metaregistrar\EPP\ficoraEppCreateContactRequest', 'Metaregistrar\EPP\eppCreateContactResponse');

This connects the function 'ficoraEppCreateContactRequest' to the response 'eppCreateContactResponse'

So unless there is a typo somewhere, this should work.
