### ISSUE TITLE
euridEpp Auth Code

### ISSUE THREAD

**Issue by fwelvering** [metaregistrar/php-epp-client#111]
When requesting the domain info for a .eu domain the authcode is not requested.
Please advise how to solve this, i use the euridEppDomainInfoRequest.

The request does not add the auth-info extension:
(for some reason the code thing is not working)

`<command>
    <login>
      <clID>XXXXXXXXXXXXXXXX</clID>
      <pw>XXXXXXXXXXXXXXXX</pw>
      <options>
        <version>1.0</version>
        <lang>en</lang>
      </options>
      <svcs>
        <objURI>urn:ietf:params:xml:ns:domain-1.0</objURI>
        <objURI>urn:ietf:params:xml:ns:contact-1.0</objURI>
        <svcExtension>
          <extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI>
          <extURI>http://www.eurid.eu/xml/epp/domain-ext-2.1</extURI>
          <extURI>http://www.eurid.eu/xml/epp/authInfo-1.1</extURI>
        </svcExtension>
      </svcs>
    </login>
    <clTRID>5a0c31e8376d6</clTRID>
  </command>
----
  <command>
    <info>
      <domain:info>
        <domain:name>*thedomain*.eu</domain:name>
      </domain:info>
    </info>
    <clTRID>5a0c31e83d552</clTRID>
  </command>
</epp>
`

**Comment by fwelvering** [comment]
``

**Comment by metaregistrar** [comment]
We will look into this issue and solve it as soon as possible.

**Comment by metaregistrar** [comment]
Hello,

I have looked into this issue, and with the latest version, if i use the euridEppInfoDomainRequest, the extension is added properly. Please make sure to use the euridEppConnection with the command parent::useExtension('authInfo-1.1');

```
  <command>
    <info>
      <domain:info>
        <domain:name>adfdefwerg.eu</domain:name>
      </domain:info>
    </info>
    <extension>
      <authInfo:info xmlns:authInfo="http://www.eurid.eu/xml/epp/authInfo-1.1">
        <authInfo:request></authInfo:request>
      </authInfo:info>
    </extension>
    <clTRID>5a1586072d458</clTRID>
  </command>
```

**Comment by fwelvering** [comment]
Hello,

Thx for your reply, we have the following code inside the euridEppConnection:
`parent::enableDnssec();
        parent::setServices(array('urn:ietf:params:xml:ns:domain-1.0' => 'domain', 'urn:ietf:params:xml:ns:contact-1.0' => 'contact'));
        parent::useExtension('domain-ext-2.1');
        parent::useExtension('authInfo-1.1');
        parent::useExtension('secDNS-1.1');`
