### ISSUE TITLE
Composer warnings

### ISSUE THREAD

**Issue by foxxlpaul** [metaregistrar/php-epp-client#118]
We get some composer warnings, for example when doing a dump-autoload:

> composer dump-autoload

Generating optimized autoload files

Warning: Ambiguous class resolution, "Metaregistrar\EPP\euridEppInfoDomainRequest" was found in both "C:\path\to\vendor/metaregistrar/php-epp-client/Protocols/EPP\eppExtensions\authInfo-
1.1\eppRequests\euridEppInfoDomainRequest.php" and "C:\path\to\ven
dor/metaregistrar/php-epp-client/Protocols/EPP\eppExtensions\registrar-1.0\eppRequests\euridEppInfoDomainRequest.php", the first will be used.

Warning: Ambiguous class resolution, "Metaregistrar\EPP\euridEppInfoDomainResponse" was found in both "C:\path\to\vendor/metaregistrar/php-epp-client/Protocols/EPP\eppExtensions\authInfo
-1.1\eppResponses\euridEppInfoDomainResponse.php" and "C:\path\to\vendor/metaregistrar/php-epp-client/Protocols/EPP\eppExtensions\registrar-1.0\eppResponses\euridEppInfoDomainResponse.php", the first will be used.

What can I do to fix these warnings?

**Comment by metaregistrar** [comment]
Yes i have seen the same error in composer - because 2 functions use the same name. Problem is when i change one of these functions, i might break code from someone that is using this function. It is a warning, not an error, and i will try to come up with a good solution.

**Comment by foxxlpaul** [comment]
Thanks for your quick response. Do you have a suggestion how to fix this manually to get rid of the warnings? Or should we just ignore?

**Comment by metaregistrar** [comment]
Please ignore for now, we will come up with a solution. Sorry about the confusion, copying one extension to another (newer) is apparently not a good idea.
