### ISSUE TITLE
Composer check out

### ISSUE THREAD

**Issue by MrAtiebatie** [metaregistrar/php-epp-client#12]
Hi,

I'm trying to clone this package with Composer only I get the following error:

`The requested package metaregistrar/php-epp-client could not be found in any version, there may be a typo in the package name.`

I copied the title from your composer.json so I'm wondering what I'm doing wrong.

Thanks,

MrAtiebatie

**Comment by metaregistrar** [comment]
Hi,

I don't know what is wrong with the package name. If i look at the naming convention on https://getcomposer.org/doc/04-schema.md#name it says; vendor name/package name, and that is what it is. 

I know of other people that have used composer to add the package, but i have no experience with composer packages myself.

**Comment by MrAtiebatie** [comment]
Ah I think you need to register your package at https://packagist.org in order to make your package available for composer downloads. Have you never used Composer? I definitely advise to look in to it because it's awesome (so is your package!).

**Comment by metaregistrar** [comment]
Added the repository to packagist. Good luck!
