### ISSUE TITLE
Missing XML in domain renew

### ISSUE THREAD

**Issue by K1ll3rM** [metaregistrar/php-epp-client#125]
I stumbled upon another problem. Whenever I send a renew request it's saying that domain:curExpDate is expected for RRPproxy and I can't seem to find anything to add that. Is there any way to add that to the request or is it a bug?

**Comment by metaregistrar** [comment]
When you make a new Metaregistrar\EPP\eppRenewRequest, it takes 2 parameters, domain name and expiration date. The expiration date you will have to get from the domain:info command. You only have to specify the date, not the time that is received from the domain:info

**Comment by K1ll3rM** [comment]
It works now, thanks!
