### ISSUE TITLE
Client transaction id does not match returned

### ISSUE THREAD

**Issue by urosgruber** [metaregistrar/php-epp-client#126]
I'm trying to figure it out if the problem is within this code or register response. 

When running **domaininfo** for a non existent domain I get first *2303* error code as "*Object does not exist*", right after this `__destruct` gets executed with logout command. The problem is the response to this logout command include clTRID id. This is not present if I get a success response from the server and run log out manually. I can provide xml if needed.

Error exception durim _desctruct is for example *Client transaction id 5a3ae26e311fc does not match returned 5a3ae26e1785d* 

Could this be a server issue on register side or is this maybe known issue with a workaround?

**Comment by metaregistrar** [comment]
It seems that there is a mismatch between messages sent and messages read. If you have sent a message with transaction id 5a3ae26e311fc and the next message read has transaction id 5a3ae26e1785d, then there are 2 possibilities:
1. You have missed to read a message somehow. You have sent 2 but read only 1
2. The registry in question is not handling its transaction ID's very nice.

**Comment by urosgruber** [comment]
I sent out email with this question to the registry to check if issue is on their end. I'll try to make a test case with all the log data and add here as a note for possible further investigation.

**Comment by alesf** [comment]
Try putting `$this->addSessionId();` to eppLogoutRequest.php

**Comment by metaregistrar** [comment]
Done

**Comment by urosgruber** [comment]
The issue was on Register side. They fixed the issue. I'll check if fixed version is on production as well.

**Comment by metaregistrar** [comment]
Great, thanks for the heads-up!

**Comment by smitpatelvi** [comment]
Also i installed latest version of package.

name     : metaregistrar/php-epp-client
descrip. : Object-oriented PHP EPP Client
keywords : domains, epp, xml
versions : * 1.0.12
