### ISSUE TITLE
Can I add new request ?

### ISSUE THREAD

**Issue by sebbio** [metaregistrar/php-epp-client#128]
My provider can response list of domain price. But need command "domain:price". Can I add this by myself. You have any examples?

**Comment by metaregistrar** [comment]
The domain:price extension is a standardized extension that is used my more registries. We are already coding to add this extension to php-epp-client as a standard feature.

**Comment by sebbio** [comment]
When you plan adding to repository?

**Comment by sebbio** [comment]
And need "balance:info" ;)

**Comment by metaregistrar** [comment]
I am not sure yet, will expedite this programming.
