### ISSUE TITLE
IIS organisation number not dynamic

### ISSUE THREAD

**Issue by sv3tli0** [metaregistrar/php-epp-client#13]
https://github.com/metaregistrar/php-epp-client/blob/master/Registries/iisEppConnection/iisEppCreateContactRequest.php

Hi, here you have hardcoded the org number. It will be nice if its possible to set it dynamic perhaps with separate method..

**Comment by metaregistrar** [comment]
Hi 

I have modified the repo to make orgno and vatno dynamic. You can either specify params on the iisCreateContact request, or call the 2 functions separately

**Comment by sv3tli0** [comment]
Great !!! Really great support from you. :+1:
