### ISSUE TITLE
Unexpected closed connection by remote host.

### ISSUE THREAD

**Issue by BrainFeeder** [metaregistrar/php-epp-client#130]
Hi we are getting the error 'Unexpected closed connection by remote host... ' when trying to connect to dns.be test env. 

$this->hostname = "ssl://epp.registry.tryout.dns.be";
$this->port = "33128";

With a username and password, configured on the dns website. We whitelisted the IP address.
If we remove ssl:// it returns the error 'Packet size is too big: 352518908. Closing connection'
Currently using php-epp-client version 1.0.2

We call 
$registrar = new \api\common\components\Registrar(['interface'=>'dnsbe', 'debug'=>true]);
$registrar->greet();

The Registrar component is a CodeIgniter library that has worked (in an other application) in the past.

**Comment by metaregistrar** [comment]
Are you sure outgoing port 33128 is open and not firewalled? Most of the time when i have checked *e erything* it is my own firewall that blocks connections.

**Comment by BrainFeeder** [comment]
Thanks for quick response. I verified with server admin and the port is both open and configured in the firewall.

**Comment by metaregistrar** [comment]
Tried connecting to the DNS Belgium OTE service with our own account, same problem

When i test the connection using this openssl command:
```openssl s_client -connect epp.registry.tryout.dns.be:33128```

I get this error: closing session, unknown ip address: 90.xxx.xxx.xxx

So it seems, that this IP address is not in the whitelist. Checked it with my OTE login, and the IP address actually is there. So it seems there is something wrong with the OTE system. You should contact DNS Belgium. 

I did try to remove and re-add the IP address, but also our passphrase on the OTE system seems to have changed, the passphrase we recorded does not function any more.

**Comment by BrainFeeder** [comment]
Found out what was wrong. Server was trying to connect with IPv6 since it is supported.

**Comment by metaregistrar** [comment]
Well, i did not think of that! Might be my problem too, i'll check. Thanks for the heads-up.

**Comment by kvanleeuwen20** [comment]
What is the main reason of this error? It lso occurs when I try to connect. I've whitelisted my ports on the firewall, whitelisted the IP's on the DNS.be registrar site and ensured that the outgoing request contains the IPV4address. But still I get the message: Packet size is too big: 352518908. Closing connection. Any clues?
