### ISSUE TITLE
Missing example: Using eppIDNA

### ISSUE THREAD

**Issue by BrainFeeder** [metaregistrar/php-epp-client#131]
I could not find this in the examples. Is it correct to do:

    ...
    $idna = new Metaregistrar\EPP\eppIDNA();
    $domain = new Metaregistrar\EPP\eppDomain($idna->encode(domainname), $registrant);
    $create = new Metaregistrar\EPP\eppCreateDomainRequest($domain, true);
    ...
Or should it be used differently?

**Comment by metaregistrar** [comment]
The eppIDNA() class is only used for encoding and decoding domain names from UTF-8 to IDNA (punycode)

So the example you are using looks correct: $idna->encode() will change the domain name from tëst.com to xn--tst-jma.com

Please note that some registries want punycode when you submit a non-ASCII domain name over EPP, others are quite fine with UTF-8 for the same domain.

**Comment by BrainFeeder** [comment]
The old system we use just encodes everything, so I'll keep doing that I guess :D 
Thanks for the tip.
