### ISSUE TITLE
Modifydomain.php Example - Error 2102: Unimplemented option

### ISSUE THREAD

**Issue by bibawa** [metaregistrar/php-epp-client#136]
Hi,

When you try to run the modifydomain.php Example on DNS Belgium it always give an error '2102 Unimplemented option'..

Anyone any idea which this could mean / any resolution to this ? 

brg,

**Comment by bibawa** [comment]
Resolved.. Seems I need to set the forcehostattr= true to get it working for DNS BE !
Thanks !

**Comment by micheldeking** [comment]
thank you bibawa this works! Was already looking for 2 hours, how did you find the answer ?
