### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by sebbio** [metaregistrar/php-epp-client#137]
Warning: Ambiguous class resolution, "Metaregistrar\EPP\euridEppInfoDomainRequest" was found in both "__PATH__\vendor/metaregistrar/php-epp-clien
t/Protocols/EPP\eppExtensions\authInfo-1.1\eppRequests\euridEppInfoDomainRequest.php" and "__PATH__\vendor/metaregistrar/php-epp-client/Protocols
/EPP\eppExtensions\registrar-1.0\eppRequests\euridEppInfoDomainRequest.php", the first will be used.
Warning: Ambiguous class resolution, "Metaregistrar\EPP\euridEppInfoDomainResponse" was found in both "__PATH__/metaregistrar/php-epp-clie
nt/Protocols/EPP\eppExtensions\authInfo-1.1\eppResponses\euridEppInfoDomainResponse.php" and "__PATH__/metaregistrar/php-epp-client/Protoc
ols/EPP\eppExtensions\registrar-1.0\eppResponses\euridEppInfoDomainResponse.php", the first will be used.

**Comment by metaregistrar** [comment]
Hi Sebbio,

We are aware of this problem, please ignore it for now. The same functions were used for 2 separate registrar extensions, and we do have to find a way to fix this without breaking user implementations.
