### ISSUE TITLE
Ficora EPP GDPR

### ISSUE THREAD

**Issue by Niko9911** [metaregistrar/php-epp-client#140]
>The General Data Protection Regulation (GDPR) will change the way contact objects are created and updated, as described in the appendix. Production deployment will be on 20.05.2018.

This will propably broke Ficora extension. I'm gonna look into this in few days using epptest -server.

**Comment by metaregistrar** [comment]
Thanks!

**Comment by Niko9911** [comment]
Okey, I just got all required information, what is going to be changed.

[Changes in the .fi domain name system imposed by the GDPR.pdf](https://github.com/metaregistrar/php-epp-client/files/1906106/Changes.in.the.fi.domain.name.system.imposed.by.the.GDPR.pdf)
[EUn tietosuoja-asetuksen tuomat muutokset Fiverkkotunnusjärjestelmään.pdf](https://github.com/metaregistrar/php-epp-client/files/1906107/EUn.tietosuoja-asetuksen.tuomat.muutokset.Fiverkkotunnusjarjestelmaan.pdf)
[Ändringar som EUs dataskyddsförordning medför i fi-domännamnssystemet.pdf](https://github.com/metaregistrar/php-epp-client/files/1906108/Andringar.som.EUs.dataskyddsforordning.medfor.i.fi-domannamnssystemet.pdf)

**Comment by metaregistrar** [comment]
"Private persons will be removed from admin-c and tech-c contacts". Do you know what happens to the domain names with those contacts? Will they have no admin-c and tech-c contacts? Are we able to update a domain name that has no admin-c or tech-c contact?

**Comment by Niko9911** [comment]
I'm forwarding this question to my tech guy at Ficora.

**Comment by Niko9911** [comment]
Just got answer... This is hard translation from Finnish:

> Otherwise, nothing happens to domain names, they do not just have Admin and tech contacts.
A user (holder) contact with all domains is always there.

**Comment by Niko9911** [comment]
> Ok, if that is acceptable, then as far as i can see nothing much has to change to php-epp-client. Just when you use php-epp-client to create a domain name, give only the registrant and no admin-c and tech-c contacts.

But only in case of the admin/tech contact is private individual.

Are you using Ficora module on production? I just wonder because few requests look little bit weird... I will integrate this code soon™️ to my project when I have time to do that. But first some testing is required. 

Anyways, like you said, there is no action needed to this client. Only for those apps using this module might need to make some changes. I see this issue as closed and more informative.

**Comment by Niko9911** [comment]
[GDPR-related changes in the EPP interface.pdf](https://github.com/metaregistrar/php-epp-client/files/1924745/GDPR-related.changes.in.the.EPP.interface.pdf)
[Ändringar i EPP-gränssnittet med anledning av GDPR.PDF](https://github.com/metaregistrar/php-epp-client/files/1924746/Andringar.i.EPP-granssnittet.med.anledning.av.GDPR.PDF)
[EPP-rajapinnan_GDPR_muutokset.pdf](https://github.com/metaregistrar/php-epp-client/files/1924747/EPP-rajapinnan_GDPR_muutokset.pdf)

@metaregistrar Got some more info about this...
