### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by kevinvdburgt** [metaregistrar/php-epp-client#143]
While using PHP 7.2, i'll get a lot of those messages:

```
count(): Parameter must be an array or an object that implements Countable
```

**Comment by jusahah** [comment]
I got similar error when using given example (from Examples directory) for creating a contact. After fixing with is_array(), I encountered following error:

```
Metaregistrar\EPP\eppException: Cannot add more then 3 street names to postal info
(/home/vagrant/lara_test/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppData/eppContactPostalInfo.php:67)
```

The problem seems to be that in eppContactPostalInfo.php, the private attribute _$this->street_ is never initialized to array...?

**Comment by metaregistrar** [comment]
Yes, of course. I have fixed that now.
