### ISSUE TITLE
Register .eu domain problem

### ISSUE THREAD

**Issue by jvdmb** [metaregistrar/php-epp-client#144]
Hello,

How do i configure the onsite contact upon registering .eu domain?

This is not working;

$domain->addContact(new eppContactHandle($admincontact, eppContactHandle::CONTACT_TYPE_ONSITE));

(Error 2001: Command syntax error (line:2 column:1015 cvc-enumeration-valid: Value 'onsite' is not facet-valid with respect to enumeration '[admin, billing, tech]'. It must be a value from the enumeration.))

This is not working;

$domain->addContact(new eppContactHandle($admincontact, eppContactHandle::CONTACT_TYPE_ADMIN));

(Error 2102: Unimplemented option; value:XXXXXXX(Contact type is not supported.))

Please help, thanks ;-)

**Comment by metaregistrar** [comment]
That is very strange: the message "(Error 2001: Command syntax error (line:2 column:1015 cvc-enumeration-valid: Value 'onsite' is not facet-valid with respect to enumeration '[admin, billing, tech]'. It must be a value from the enumeration.))" is this coming back from the registry? That would mean that they do not accept the value 'onsite' for a contact type. Can you enable logging to see what is sent to the registry and what is coming back?

**Comment by metaregistrar** [comment]
The 'onsite' parameter should not be set with the ->addContact option, but you specify 'onsite' when creating a new contact (euridEppCreateContactRequest)

**Comment by jvdmb** [comment]
But when registering a domain we re-use the contact we already have in our database (c163 f.e.). So no need to use euridEppCreateContactRequest right?

Eurid requires extension;

   <extension>
      <domain-ext:create xmlns:domain-ext='http://www.eurid.eu/xml/epp/domain-ext-2.1'>
        <domain-ext:contact type='onsite'>c163</domain-ext:contact>
        <domain-ext:contact type='reseller'>c164</domain-ext:contact>
      </domain-ext:create>
    </extension>

So maybe the standards are not working?

**Comment by metaregistrar** [comment]
The extension domain-ext-2.1 is partially created in php-epp-client. It seems that only the domain:transfer function is programmed, but not the domain:create function. I will see if this is easy to add in the repository.

**Comment by jvdmb** [comment]
Any update on this? :-)
Thanks!

**Comment by metaregistrar** [comment]
Hi,
I have just tested and committed the euridEppCreateDomain.php command. With this you can create domain names with EurID. Please make sure that you use euridEppCreateContact commands to create the appropriate contacts, and give them the 'registrant', 'onsite', or 'billing' type.
