### ISSUE TITLE
Error when trying to register a domain

### ISSUE THREAD

**Issue by jjclinton** [metaregistrar/php-epp-client#147]
Hi when I try to register a domain  on ssl://testdrs.domain-registry.nl I get this error:  
The number of field/message component occurrences is incorrect (min=1, max=1)

I don't know what this means, could you please explain?

The problem is in this function: $contactid = createcontact($conn,'test@gmail.com','+31.612413333','jay','brisp','Pomme 1','7905BA','Amsterdam','NL');

function createcontact($conn, $email, $telephone, $name, $organization, $address, $postcode, $city, $country) {
    /* @var $conn Metaregistrar\EPP\eppConnection */
    try {
        $contactinfo = new eppContact(new eppContactPostalInfo($name, $city, $country, $organization, $address, 'Drenthe', $postcode, Metaregistrar\EPP\eppContact::TYPE_LOC), $email, $telephone);
        //$contactinfo->setPassword('fubar');
        $contact = new eppCreateContactRequest($contactinfo);
        if ($response = $conn->request($contact)) {
            /* @var $response Metaregistrar\EPP\eppCreateContactResponse */
            echo "Contact created on " . $response->getContactCreateDate() . " with id " . $response->getContactId() . "\n";
            return $response->getContactId();
        }
    } catch (eppException $e) {
        echo 'CREATECONTACT ERROR:' . $e->getMessage() . "\n";
        $conn->logout();
    }
    return null;
}

**Comment by metaregistrar** [comment]
Hi Josh

for .NL, SIDN wants extra parameters to be supplied when creating a new contact. The example code does not take this into account.

So for .NL, use sidnEppCreateContactRequest to create a contact, it will supply the extra parameters to SIDN.

**Comment by jjclinton** [comment]
Awesome, it works. Thank you!
