### ISSUE TITLE
Change Autorenew settings

### ISSUE THREAD

**Issue by qarizma** [metaregistrar/php-epp-client#148]
Hello,

I am not sure if there is a function to adjust the autorenew function? In particular for the SIDN registry.
Does anyone have an example for this?

Thanks!

**Comment by metaregistrar** [comment]
SIDN does not support an autorenew function. You can delete domain names right now, and since 2018 they have a function to delete domain names in the future. But this last item has not been added to SIDN EPP yet. So for now you only have the possibility to delete domain names right now via EPP.

**Comment by qarizma** [comment]
Okay thank you!
