### ISSUE TITLE
Get message from sidn extension

### ISSUE THREAD

**Issue by tomalbers** [metaregistrar/php-epp-client#149]
Hi,

Whenever something goes wrong with the connection we get a nice exception, but the real message is not shown. The response is like:

`<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:sidn-ext-epp="http://rxsd.domain-registry.nl/sidn-ext-epp-1.0">
  <response>
    <result code="2200">
      <msg>Validation of the transaction failed.</msg>
    </result>
    <extension>
      <sidn-ext-epp:ext>
        <sidn-ext-epp:response>
          <sidn-ext-epp:msg code="C0033a" field="New password">Invalid password: a password must contain a minimum of 10 characters.</sidn-ext-epp:msg>
        </sidn-ext-epp:response>
      </sidn-ext-epp:ext>
    </extension>
    <trID>
      <clTRID>5b08a3e6497d8</clTRID>
      <svTRID>D3074A84-6928-DA21-1790-A50F2AC086EC</svTRID>
    </trID>
  </response>
</epp>`

The exception shows "Error 2200: Validation of the transaction failed.", but would it be possible to get to the "Invalid password: a password must contain a minimum of 10 characters." message?

**Comment by metaregistrar** [comment]
Yes, it is too bad that SIDN puts this error message in a proprietary extension. I will check to see if there is an extension that will process this.
