### ISSUE TITLE
Connection with SIDN timing out

### ISSUE THREAD

**Issue by damiaanr** [metaregistrar/php-epp-client#150]
Dear developers,

I keep getting a time-out on connecting with SIDN, accompanied with the following PHP error:

> Warning: stream_socket_client(): unable to connect to ssl://drs.domain-registry.nl:700 (Connection timed out) in (...)/SIDN/Protocols/EPP/eppConnection.php on line 386

I have tried connecting to port 7000 and 700 and either with and without "ssl://". I am totally sure my login credentials are correct, and I assume SIDN will throw an error instead of timing out. I contacted SIDN over this issue, they replied by saying that an error in the script error causes the time-out. They sent me the following login-command, which they state is not coming through properly:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?><epp xmlns="urn:ietf:params:xml:ns:epp-1.0"><command><login><clID>USERNAME</clID><pw>PASSWORD</pw><options><version>1.0</version><lang>en</lang></options><svcs><objURI>urn:ietf:params:xml:ns:con tact-1.0</objURI><objURI>urn:ietf:params:xml:ns:host-1.0</objURI><objURI>urn:ietf:params:xml:ns:domain-1.0</objURI><svcExtension><extURI>http://rxsd.domain-registry.nl/sidn-ext-epp-1.0</extURI></svcExtension></svcs></login><clTRID>LOGIN</clTRID></command></epp>`
What am I missing? Thank you very much!

**Comment by metaregistrar** [comment]
Port should be 700 for SIDN connections

Please make sure your IP address is whitelisted in the SIDN back-end. And please make sure that no outgoing connections to port 700 are blocked on your own firewall - many people miss that last one...
