### ISSUE TITLE
Poll function not working for DNS BE

### ISSUE THREAD

**Issue by bibawa** [metaregistrar/php-epp-client#152]
Hi,

I'm trying to get the poll function working for DNS Belgium. At dns.be the php poll function has been enabled but when I try to run the example script it always says "command completed successfully; no messages" even i tried to transfer away domainnames in our test account and also did some new registrations..

Any idea what this could be ?

**Comment by metaregistrar** [comment]
I think you have to login to the DNS Belgium back-end, and enable poll messages via EPP. They will send you all messages via E-mail until you indicate you want the messages over EPP.
