### ISSUE TITLE
Error connecting to ssl://registry:700:  (code 0)

### ISSUE THREAD

**Issue by gumisirizab1** [metaregistrar/php-epp-client#153]
Hi team, anyone who could have faced this kind of issue or anyone to assist will be grateful
Metaregistrar\\EPP\\eppException\' with message \'Error connecting to ssl://registry.********:700:  (code 0)

**Comment by metaregistrar** [comment]
2 possibilities:
- You have not whitelisted your IP address with the registry
- Your own firewall is blocking outgoing port 700 traffic

**Comment by gumisirizab1** [comment]
Hi, thanks for your response, what I am sure of is that the firewall is not blocking the port 700 but I will check with the registry to see if its the one blocking the IP and get back to you
