### ISSUE TITLE
Openprovider wrong command name

### ISSUE THREAD

**Issue by jjclinton** [metaregistrar/php-epp-client#154]
Hello, I'm having EPP for SIDN set up and it works. However, when I do the exact same thing with Openprovider, it logs in and then says '4001 wrong command name'. Do you know where I should look to resolve this?

**Comment by metaregistrar** [comment]
Do you have a line number with the error or output to help me find the problem?

**Comment by jjclinton** [comment]
Sorry for the late response. The issue is resolved. Thanks.

**Comment by cliffordjames** [comment]
I had the same issue, make sure you use epp.openprovider.eu instead of api.openprovider.eu and set the port to 443.
