### ISSUE TITLE
DNSBE - Nameserver group change

### ISSUE THREAD

**Issue by bibawa** [metaregistrar/php-epp-client#155]
Hi,

Couple of weeks ago you added support to retreive nameserver group information.. Will you update the code as wel to support change of NS group information ? 

thank you

**Comment by maehdros** [comment]
Hi, I have created a pull request with a new feature (delete dnsbe nsgroup).
I will add the update nsgroup on the branch (maehdros/php-epp-client) probably today.

**Comment by metaregistrar** [comment]
pull request is merged with the main branch
