### ISSUE TITLE
SSL Handshake Timeout - Error connecting (code 0)

### ISSUE THREAD

**Issue by marpaul** [metaregistrar/php-epp-client#158]
I am able to connect Test Environment perfectly with this client. 
But when trying to connect Production Environment, i am facing the below error - 
SSL Handshake Timeout - Error connecting (code 0)

If we add SSL certificate of registry server in truststore - then the issue may be solved. 
Any ways to add SSL in truststore in this client.

Kindly advise for the above 2 issues.

**Comment by metaregistrar** [comment]
You can add certificates (PEM files) with the following entries in the connection .INI file:

certificatefile=/home/xxxxxx/xxxxxxx.pem
certificatepassword=xxxxxxx

**Comment by manishrpal** [comment]
I have already added my certificates (PEM files) in .INI file.

I was asking about adding registry server certificate as truststore. They have given me certificate file and also said that the SSL handshake will be fast if added.
Is it possible to add registry server certificate ?

**Comment by metaregistrar** [comment]
For PEM files, you can add certificates simply by concatenating the files together. You can create one PEM file that contains all the certificates you need: Root certificates, server certificates, your own certificate, alle in one text file.

**Comment by marpaul** [comment]
After concatenating all the certificates, it is giving certificate error. I was sure this will not work but it was worth trying. 
Test environment is working, but Production environment is not working.
I think there may be some port blocking on my server. 
Kindly advise how your script is working - after request on EPP port 700 - how we get the response ?
Is the response we get is also on port 700 ?
Kindly advise.

**Comment by metaregistrar** [comment]
Yes, a connection is made and the response is on the same port. What registry are you connecting to? We have connections to 100+ registries, so we may have had the same issue as you.

**Comment by metaregistrar** [comment]
Handled this problem via direct e-mail
