### ISSUE TITLE
DNS Belgium will stop supporting TLS 1.0 and 1.1 on EPP

### ISSUE THREAD

**Issue by wouterca** [metaregistrar/php-epp-client#161]
Hello,

DNS Belgium would stop supporting TLS 1.0 and 1.1 on EPP at the end of November.
Will this be a concern? 
Unless I'm mistaken, the current connection uses SSLv3 in php-epp-client at the moment.

Thanks in advance,

Wouter

**Comment by metaregistrar** [comment]
Hello Wouter,

The php-epp-client does not specify an encryption method upon connection, but relies on the standard negotiation of the openssl libraries. 

we have not encountered any problems connecting to DNS Belgium test services so far, but i do not know if the test services have already dropped tls-1.0 and tls-1.1

**Comment by wouterca** [comment]
They will apparently drop it on the test server one week before they implement it on the production server.   
So as long as we have at least openssl 1.0.1 (when TLS 1.2 was added), we should be ok.
