### ISSUE TITLE
question: reseller option?

### ISSUE THREAD

**Issue by kvanleeuwen20** [metaregistrar/php-epp-client#170]
Hello, is there a reseller option in the SidnEppClient?
You can set a reseller (CRUD) for a domainname?
Is there information available?

**Comment by metaregistrar** [comment]
No, we have not had the time yet to add the SIDN reseller extensions to the package. Feel free to add them to the extensions and create a pull request, i do not know when we will get around to doing it.

**Comment by xodroid** [comment]
Is this for being able to have resellers for the TLD that you are selling using this client? I hope it gets supported!

**Comment by metaregistrar** [comment]
This repository relied heavily on the contributions of the programmers using it. Missing an option? Please add it and issue a pull request to have your code added to the repository.
