### ISSUE TITLE
question: other parties

### ISSUE THREAD

**Issue by kvanleeuwen20** [metaregistrar/php-epp-client#171]
hello,

Is it also possible to support other suppliers, like, e..g:
- Nominet
- CentralNic
- ICANN
- Denic etc.?

Is there information available about this subject or is it something what's on the schedule?

**Comment by metaregistrar** [comment]
ICANN is not a domain name registry.

You can see the supported registries in the /Registries subdirectory. Some implementation were created by other parties, so every implementation is different.
