### ISSUE TITLE
Readme adjusment

### ISSUE THREAD

**Issue by edermartins** [metaregistrar/php-epp-client#172]
There are two errors in the README code sample:

1. Statement new is missing:
"$conn = Metaregistrar\EPP\eppConnection();" should be "$conn = **new** Metaregistrar\EPP\eppConnection();"

2. Hostname cannot receive the protocol 'ssl://':
"$conn->setHostname('ssl://eppltest1.metaregistrar.com');" should be "$conn->setHostname('eppltest1.metaregistrar.com');"

**Comment by metaregistrar** [comment]
I fixed the first one, the second one i will have to test, because the server *should* accept SSL connections.

**Comment by metaregistrar** [comment]
Checked it, and eppltest1.metaregistrar.com does actually support SSL connections over port 7000

Please make sure that your IP address is whitelisted, and make sure that outgoing port 7000 is not blocked on your development environment.

**Comment by metaregistrar** [comment]
Aha, okay, that is specific to the $conn->setHostname('ssl://eppltest1.metaregistrar.com'); method of connecting. Please let me check and fix this, there is a pull request open with a fix.

**Comment by edermartins** [comment]
Great and thanks :-)

**Comment by metaregistrar** [comment]
The latest version is redone now to make sure that settings are processed exactly the same way, no matter how they are provided to the system. Added Examples/alternativeconnection.php to test and make sure this works.
