### ISSUE TITLE
Connection Without SSL

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#179]
Hey Guys,

ok so with the co.za EPP we have the live EPP and the OT&E system. The OT&E allows me to test commands... Now my issue is, since updating to the newest version, It keeps giving me errors like: Connection could not be opened: 0

There is no certificate so I disable SSL (The OT&E requires ssl to be off)... I am not sure what I should do to correct this?
Using ssl://coza-otande.registry.net.za no longer works, So I am not sure how to correct. Can you please advise?

**Comment by metaregistrar** [comment]
For both OTE and live you need an SSL certificate. The website of ZACR allows you to upload the public key of the certificate onto their site, and only after that the SSL connection will work. And you need to whitelist IP addresses of course, also in the OTE.

**Comment by swartjie** [comment]
The OT&E I can connect without SSL, Question though... How can I fully disable ssl on the connection to test?
