### ISSUE TITLE
Error 2400: Command failed

### ISSUE THREAD

**Issue by gumisirizab1** [metaregistrar/php-epp-client#181]
Any one to assist on what could be the cause of this error message below
**Error 2400: Command failed**

**Comment by metaregistrar** [comment]
Without any context, it is difficult to see what is wrong. Please log the EPP conversation and show the complete EPP response for the failing command.

**Comment by gumisirizab1** [comment]
Thanks for your feedback, I also contact the Server that I communicated to and they realized that the server IP I was using to communicate to Registry was not white-listed. After white-listing everything worked.
Thanks
