### ISSUE TITLE
Domain Info Returns NULL On Status

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#183]
Hey Guys,

I trust you are well?
It seems for some reason that if I don't own a domain, that the domaininfo check does not return the domain status, it just returns NULL...

Which means I can't check if the transfer failed and is no longer in pendingTransfer state, Can you please advise what I can do in the class to check?

**Comment by metaregistrar** [comment]
Hi there,

Is this on our service (Metaregistrar) or do you have this problem with another registry?

**Comment by swartjie** [comment]
It's using the Metaregistrar class, but with the COZA Registry (registry.net.za)

**Comment by metaregistrar** [comment]
We do not have this experience with ZACR. When i query a domain name that is not ours i do get basic information about that domain name. When i query a domain name that is not registered, i get this:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<epp:epp xmlns:epp="urn:ietf:params:xml:ns:epp-1.0">
  <epp:response>
    <epp:result code="2303">
      <epp:msg>Domain does not exist</epp:msg>
    </epp:result>
    <epp:trID>
      <epp:clTRID>5cbebafd1d02d</epp:clTRID>
      <epp:svTRID>COZA-EPP-16A490A6D28-26ABD</epp:svTRID>
    </epp:trID>
  </epp:response>
</epp:epp>
```
