### ISSUE TITLE
Example uses obsolete function

### ISSUE THREAD

**Issue by WilliamDEdwards** [metaregistrar/php-epp-client#184]
The 'removednssec.php' example file uses `getKeydata()` (which doesn't work by the way) but the function is obsolete:

```
    /**
     * OBSOLETE, DO NOT USE THIS FUNCTION
     * If you need DNSSEC KeyData or DSData, see the extension SecDNS-1.1
     * ALL DNSSEC FUNCTION ARE IN THERE
     * @return array|null
     */
```

**Comment by metaregistrar** [comment]
Thanks for the heads-up!

The example file has been modified to use the SecDNS-1.1 extension instead of the obsolete function
