### ISSUE TITLE
Error in getNsgroupHosts

### ISSUE THREAD

**Issue by denjaland** [metaregistrar/php-epp-client#200]
Hi,

Just created PR #199 to resolve an issue where the foreach loop was not given the correct array to loop over when getting nsgroup info from DNS BE.

Thanks for pulling it in at your soonest convenience :-)

**Comment by metaregistrar** [comment]
Merged! Thanks.

**Comment by denjaland** [comment]
Thanks, @metaregistrar!  What is your policy on when you tag a new release?

**Comment by denjaland** [comment]
Hi again @metaregistrar - any idea on when you're tagging a new release, so I can pull in this change? :-)  #prettyplease

**Comment by denjaland** [comment]
Hi @metaregistrar , can you please release a new version with this fix?

**Comment by metaregistrar** [comment]
Will do this week.

**Comment by denjaland** [comment]
Hiya,

You think this week is feasible?  I keep forgetting I need to patch this every time we do a new deploy :-)

**Comment by denjaland** [comment]
Hi @metaregistrar,

Are you still releasing this, or should I just fork it now?
Thanks!

David.

**Comment by metaregistrar** [comment]
Hi David,

My apologies, i forgot the release. Will do it today.

**Comment by metaregistrar** [comment]
Done, 1.0.8 released
