### ISSUE TITLE
Norid epp transfer request parse error

### ISSUE THREAD

**Issue by joveice** [metaregistrar/php-epp-client#202]
Request:
```
-----WRITE-----2019-06-14 10:00:31-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1" xmlns:no-ext-epp="http://www.norid.no/xsd/no-ext-epp-1.0" xmlns:no-ext-result="http://www.norid.no/xsd/no-ext-result-1.0" xmlns:no-ext-domain="http://www.norid.no/xsd/no-ext-domain-1.1" xmlns:no-ext-contact="http://www.norid.no/xsd/no-ext-contact-1.0" xmlns:no-ext-host="http://www.norid.no/xsd/no-ext-host-1.0">
  <extension>
    <command xmlns="http://www.norid.no/xsd/no-ext-epp-1.0">
      <clTRID>***</clTRID>
    </command>
  </extension>
</epp>

-----END-----2019-06-14 10:00:31-----
```
Response:
```
-----READ-----2019-06-14 10:00:31-----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:ietf:params:xml:ns:epp-1.0" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2001">
      <msg>Command syntax error</msg>
    </result>
    <extension>
      <conditions xmlns="http://www.norid.no/xsd/no-ext-result-1.0" xsi:schemaLocation="http://www.norid.no/xsd/no-ext-result-1.0 no-ext-result-1.0.xsd">
        <condition code="EC000015" severity="error">
          <msg>EPP parse error</msg>
          <details>Parse error at line [2], column [1871]: Element '{http://www.norid.no/xsd/no-ext-epp-1.0}clTRID': This element is not expected. Expected is one of ( {http://www.norid.no/xsd/no-ext-epp-1.0}transfer, {http://www.norid.no/xsd/no-ext-epp-1.0}withdraw ).
</details>
        </condition>
      </conditions>
    </extension>
    <trID>
      <svTRID>***</svTRID>
    </trID>
  </response>
</epp>

-----END-----2019-06-14 10:00:31-----
```
Code:
```
$domain = new noridEppDomain($domain);
$domain->setAuthorisationCode($code);
$transfer = new noridEppTransferRequest(eppTransferRequest::OPERATION_REQUEST, $domain);
$this->conn->request($transfer);
```
I'm not sure what is wrong or if I'm missing something, the request looks quite empty.
Due to https://github.com/metaregistrar/php-epp-client/commit/551d3c06b1e2c5f147ca161ea38473bbb96da8ae I'm gonna guess it has worked / is working but I do it wrong. @alexrsagen mind taking a look?

**Comment by alexrsagen** [comment]
I assume that you want to **execute** a domain transfer and not **request** a Norid transfer token here.

`eppTransferRequest::OPERATION_REQUEST` is wrong for Norid transfers... You must specify `noridEppTransferRequest::OPERATION_EXECUTE` if you wish to execute a domain transfer with a known authInfo code. This is Norid-specific. See [the Norid EPP documentation](https://www.norid.no/uploads/2017/11/EPP_Interface_Specification.0e1.pdf) page 27.

However if you want to request a Norid transfer token in a case where authInfo code is not known, you can specify `eppTransferRequest::OPERATION_REQUEST` and ensure notify email is set on the `noridEppDomain` object. This seems to currently be broken, I will fix that now.

**Comment by joveice** [comment]
Okey, yes I believe that would be correct since I know the code. Now this did return an exception:
```
ErrorException (E_USER_NOTICE)
Operation parameter should be QUERY, REQUEST, CANCEL, APPROVE or REJECT on eppTransferRequest, ignore this if you are using a custom transfer operation
```
Now it says I can ignore this, but I don't see how I can ignore an exception thrown by the function call.
Thanks for the quick response!

**Comment by alexrsagen** [comment]
That is an `E_USER_NOTICE`. It does not interrupt code execution at all, your code will function normally. To suppress the notice, you may prepend an `@` to the command which causes the notice.

Example:
```php
@$this->conn->request($transfer);
```

**Comment by joveice** [comment]
Thanks a lot @alexrsagen. It's working.
the `@` had to be placed at the new noridEppTransferRequest since that was what threw the exception, confused me too first as I thought it was the conn->request :P
