### ISSUE TITLE
adding afnic registry

### ISSUE THREAD

**Issue by aqueos** [metaregistrar/php-epp-client#204]
hi,

  just if you are willing to add the nic.fr registry. I have succefully connected with the attached file.

[eppConnection.txt](https://github.com/metaregistrar/php-epp-client/files/3305527/eppConnection.txt)

**Comment by aqueos** [comment]
i added it in the Registries/afnicEppConnection/eppConnection.php file :)

**Comment by metaregistrar** [comment]
The method you have used will give you a login to Afnic, but will not enable you to use the additional functions that the extension frnic-1.4 holds. It is better to program these functions in Protocols/EPP/eppExtensions so that they can actually be used by you and other users of this repo.

**Comment by aqueos** [comment]
Le 17/07/2019 à 14:16, Ewout de Graaf a écrit :
> The method you have used will give you a login to Afnic, but will not enable you to use the additional functions that 
> the extension frnic-1.4 holds. It is better to program these functions in Protocols/EPP/eppExtensions so that they can 
> actually be used by you and other users of this repo.

ok, will try to see how to do that because as i am not a dev at all, i struggle a lot :)

Ghislain.
