### ISSUE TITLE
Checking Domain Transfer Status COZA

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#206]
Hey Guys,

I love the class. Working wonders!!!
One issue I am struggling to solve though, How can I go about checking the status of a domain transfer for the co.za extensions?

There is an advised xml to run:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <command>
    <transfer op="query">
      <domain:transfer xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
        <domain:name>example.test.dnservices.co.za</domain:name>
      </domain:transfer>
    </transfer>
    <clTRID>ABC-12345678901</clTRID>
  </command>
</epp>

But I can't find a similar function in the EPP Client... Can you maybe advise how I can go about doing it?

**Comment by metaregistrar** [comment]
I am not sure about the CO.ZA extension, but the standard way of work for EPP is to create an eppTransferRequest with eppTransferRequest::OPERATION_QUERY as parameter. 
There are 5 possible parameters to the eppTransferRequest
OPERATION_QUERY: Request the status of an active transfer
OPERATION_REQUEST: Request a new transfer
OPERATION_CANCEL: Cancel a running transfer
OPERATION_APPROVE: Approve an outgoing transfer request
OPERATION_CANCEL: Cancel an outgoing transfer request

However, i must say that not all registries have implemented all 5 of them, so i am not sure where ZACR stands on this.
