### ISSUE TITLE
Deleting Domain Contacts

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#207]
Hey Guys,

Can you please advise how we can go about deleting a contact?
I can't seem to find anything in the class for it...

**Comment by metaregistrar** [comment]
$contact = new eppContactHandle($contactid);
$command = new eppDeleteContactRequest($contact);
if ($response = $conn->request($command)) {
}

**Comment by swartjie** [comment]
Worked like a charm thank you :)
