### ISSUE TITLE
Cancelling A Domain Transfer Request

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#209]
Hey Guys,

So far I am inlove with your class & support. Thanks for all the assistance getting the coza system working with it. I just have one more issue that I am having trouble resolving. We can cancel domain transfer requests in order to request it again...

How can I go about getting this working with your class?
Can you please advise?

Example XML Code:
<epp:epp xmlns:epp="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
	<epp:command>
		<epp:transfer op="cancel">
			<domain:transfer>
				<domain:name>$domain</domain:name>
			</domain:transfer>
		</epp:transfer>
	</epp:command>
</epp:epp>

**Comment by metaregistrar** [comment]
Basically the same as requesting the transfer, only using OPERATION_CANCEL instead of OPERATION_REQUEST. But the command is the same.

**Comment by swartjie** [comment]
Awesome thank you. Quick question though in addition to this...
Is there anyway to run clean XML through the connection.

So on other words, Logging in like normal, then instead of building a renew request for example. Running clean XML?
It does not have to process the response. it can just output it as string or something. It's basically for the odd case where something isn't lekker and I want to manually fix it fast.

**Comment by metaregistrar** [comment]
Yes, basically you can use $response  = $conn->request($string) with any XML. So in normal cases you would build $string with php-epp-client functions, but you can also fill $string with any XML command you wish as a complete string and then perform $conn->request($string) to send it through the connection.

**Comment by swartjie** [comment]
Awesome thank you bud. Keep up the good work!
