### ISSUE TITLE
PHP Strict error

### ISSUE THREAD

**Issue by pkaz** [metaregistrar/php-epp-client#21]
Declaration of Metaregistrar\EPP\eppHttpConnection::read() should be compatible with Metaregistrar\EPP\eppConnection::read($nonBlocking = false) in ./vendor/metaregistrar/php-epp-client/Protocols/EPP/eppHttpConnection.php on line 13

What happens here is that the declaration of the read function in eppHttpConnection is not identical to the read function in eppConnection. The latter takes a parameter "$nonBlocking" while the former takes none. 

I guess this is a problem for those who have error_reporting set to E_STRICT. 

*this is my first ever Issue Reporting, so I hope I did this the right way.

**Comment by metaregistrar** [comment]
You did great! The issue has been resolved in the latest push.
