### ISSUE TITLE
How to get the nameserver last update date?

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#222]
Hey Guys,

How can one go about getting the last update date for nameservers?
I Can only find references to getting the IP and the nameserver itself... How can we get the actual update date?

Thanks for the assistance!

**Comment by metaregistrar** [comment]
You can only get the last update date for the domain name - and then you still don't know what has been updated. There is no last-update date for nameservers.

**Comment by swartjie** [comment]
How is that then implicated with RDAP apparently requiring the NS record update date aswell? Or did I miss something?

I saw on some of the service providers rdap links that the ns update date's are included?

**Comment by metaregistrar** [comment]
It seems that the RDAP RFC's mix nameservers with hostnames.

In EPP, a hostname (a sub-ordinate nameserver to a domain name) can have IP addresses and last update data. 
A nameserver (when you connect a nameserver to a domain name) cannot. You cannot specify the IP address and you cannot see the last update date.

But if you have subordinate nameserver to a domainname (for example if you own hostingserver.com and you also own ns1.hostingserver.com and ns2.hostingserver.com), those are called Hosts (not nameservers) in EPP, and you define and query them with an eppHost object.

**Comment by swartjie** [comment]
Sorry I conflated the two... I am looking for the sub-ordinate nameserver last update date?

**Comment by metaregistrar** [comment]
I think that is it, yes

**Comment by swartjie** [comment]
Ok now the question is can I do it with your class though?

**Comment by metaregistrar** [comment]
If it is a subordinate host, yes. Use the eppInfoHostRequest, and with the result retrieve getHostUpdateDate()
