### ISSUE TITLE
EurID schema update

### ISSUE THREAD

**Issue by BCooperA** [metaregistrar/php-epp-client#224]
I've already noticed that you have started implementing the schema changes for EurID XML requests. When can we expect the feature to be fully implemented?

**Comment by metaregistrar** [comment]
Well, we are dependent on the contributions of the users of this repository. It is impossible for us to keep up with all the changes the registries present. If there are things you really need i can add them on short notice, but a full implementation will take time

**Comment by alesf** [comment]
It’s mostly done anyways. Some of the peculiarities do not touch requests or responses directly. For example registrant contact needs to be updated with provided naturalPerson attribute before you can update the domain, etc.
