### ISSUE TITLE
Error 2001: Command syntax error (checkdomain)

### ISSUE THREAD

**Issue by CElysee** [metaregistrar/php-epp-client#228]
Hello, 
I have been trying to checkdomain but I'm getting Error 2001: Command syntax error and i don't really know what I'm doing wrong.

I tried to dump ($check = new eppCheckDomainRequest($domains);) and this what i'm getting.

eppCheckDomainRequest {#210 ▼
  -forcehostattr: false
  +domainobject: DOMElement {#209 ▶}
  +epp: DOMElement {#207 ▶}
  +command: DOMElement {#201 ▶}
  +extension: null
  +sessionid: "5dceea6beb2fb"
  +login: null
  +hello: null
  -namespacesinroot: true
  +nodeName: "#document"
  +nodeValue: null
  +nodeType: XML_DOCUMENT_NODE
  +parentNode: null
  +childNodes: DOMNodeList {#221 ▶}
  +firstChild: DOMElement {#207 ▶}
  +lastChild: DOMElement {#207 ▶}
  +previousSibling: null
  +nextSibling: null
  +attributes: null
  +ownerDocument: null
  +namespaceURI: null
  +prefix: ""
  +localName: null
  +baseURI: null
  +textContent: ""
  +doctype: null
  +implementation: DOMImplementation {#227 ▶}
  +documentElement: DOMElement {#207 ▶}
  +actualEncoding: "UTF-8"
  +encoding: "UTF-8"
  +xmlEncoding: "UTF-8"
  +standalone: true
  +xmlStandalone: true
  +version: "1.0"
  +xmlVersion: "1.0"
  +strictErrorChecking: true
  +documentURI: null
  +config: null
  +formatOutput: true
  +validateOnParse: false
  +resolveExternals: false
  +preserveWhiteSpace: true
  +recover: false
  +substituteEntities: false
  xml: """
    <?xml version="1.0" encoding="UTF-8"?>
    <epp>
      <command>
        <check>
          <domain:check/>
        </check>
        <clTRID>5dceea6beb2fb</clTRID>
      </command>
    </epp>
    """
}

it looks like something is missing in XML.

Thank you.

**Comment by metaregistrar** [comment]
Hello,

I would like to help you, but your XML is not readble. Please use the triple quotes in Github to mark code so that the XML shows properly.
