### ISSUE TITLE
Error 2202: Invalid authorization information; Incorrect Authcode provided. (InfoDomain)

### ISSUE THREAD

**Issue by CElysee** [metaregistrar/php-epp-client#229]
Hello,
I'm trying to check the info on a domain but I'm getting this error(Error 2202: Invalid authorization information; Incorrect Authcode provided.)

Does anyone know what's wrong?

-----READ-----2019-11-15 20:21:15-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2202">
      <msg>Invalid authorization information; Incorrect Authcode provided.</msg>
    </result>
    <trID>
      <clTRID>5dcefaab584a9</clTRID>
      <svTRID>1573845675446</svTRID>
    </trID>
  </response>
</epp>

-----END-----2019-11-15 20:21:15-----

-----WRITE-----2019-11-15 20:21:15-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0">
  <command>
    <logout></logout>
    <clTRID>5dcefaab9c831</clTRID>
  </command>
</epp>

-----END-----2019-11-15 20:21:15-----

-----READ-----2019-11-15 20:21:15-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
  <response>
    <result code="1500">
      <msg>Command completed successfully; ending session</msg>
    </result>
    <trID>
      <clTRID>5dcefaab9c831</clTRID>
      <svTRID>1573845675675</svTRID>
    </trID>
  </response>
</epp>

-----END-----2019-11-15 20:21:15-----

-----LOGOUT-----2019-11-15 20:21:15-----
Logged out
-----END-----2019-11-15 20:21:15-----

-----DISCONNECT-----2019-11-15 20:21:15-----
Disconnected
-----END-----2019-11-15 20:21:15-----

Thank you.

**Comment by metaregistrar** [comment]
It seems that you are querying a domain name that is not in your portfolio. If you try to do a domain:info on a domain name that belongs to another registrar, you need to provide the correct authcode to prove that you are authorized to view the information.

When you domain:info a domain name in your own portfolio, an authcode is not needed.
