### ISSUE TITLE
feature for telephone extension

### ISSUE THREAD

**Issue by xikyu46** [metaregistrar/php-epp-client#23]
I try to  find option to set telephone extension in eppcontact. But i couldn't find a way how we can set telephone extension using php-epp-client.

**Comment by metaregistrar** [comment]
You mean in a contact?

Please review Examples/createcontact.php

$postalinfo = new Metaregistrar\EPP\eppContactPostalInfo($name, $city, $country, $organization, $address, null, $postcode);
    $contactinfo = new Metaregistrar\EPP\eppContact($postalinfo, $email, $telephone);
    $contactinfo->setPassword('');
    $contact = new Metaregistrar\EPP\eppCreateContactRequest($contactinfo);

The telephone number is in new Metaregistrar\EPP\eppContact

**Comment by metaregistrar** [comment]
The EPP RFC (https://tools.ietf.org/html/rfc5733) has no provision for a telephone extension, only a telephone number.

In paragraph 2.5 the following is said about an extension:

Contact telephone number structure is derived from structures defined
   in [ITU.E164.2005].  Telephone numbers described in this mapping are
   character strings that MUST begin with a plus sign ("+", ASCII value
   0x002B), followed by a country code defined in [ITU.E164.2005],
   followed by a dot (".", ASCII value 0x002E), followed by a sequence
   of digits representing the telephone number.  An optional "x"
   attribute is provided to note telephone extension information.

So the way to represent a telephone number with extension would be:
+1.5539488x433
