### ISSUE TITLE
Missing Domain Name Renew

### ISSUE THREAD

**Issue by mrclick** [metaregistrar/php-epp-client#230]
Hello,

It looks like you forgot to add the domain renew file. Could you kindly add the renew domain file in Examples. 

Regards,

**Comment by metaregistrar** [comment]
I have added example domain renew code. Please review https://github.com/metaregistrar/php-epp-client/blob/master/Examples/renewdomain.php

Please note that i have not tested this example code yet.

**Comment by mrclick** [comment]
I tested it and get this error: "Error 2202: Invalid authorization information; Incorrect Authcode provided." 

Could you kindly double check if domain:info is working perfectly because when i try to get domain info, it returns the same error yet the domain i'm checking are under my account.

Thanks.
