### ISSUE TITLE
Error 2202: Invalid authorization information; Incorrect Authcode

### ISSUE THREAD

**Issue by mrclick** [metaregistrar/php-epp-client#232]
Hello,

I'm getting this error: "Error 2202: Invalid authorization information; Incorrect Authcode provided." when using domain:info .

The domain I'm checking are under my account. Why does it require Authcode?
Can you kindly, double check if the domain:info code are okay.

Regards

**Comment by metaregistrar** [comment]
The code is okay - it is used by many companies around the world.
Can you post the request and response XML in this thread? (without the data that is sensitive?)

**Comment by mrclick** [comment]
Thanks for your prompt response, Find below the XML:

`-----LOGIN-----2019-11-19 16:26:43-----
Logged in
-----END-----2019-11-19 16:26:43-----

-----WRITE-----2019-11-19 16:26:43-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0">
  <command>
    <info>
      <domain:info>
        <domain:name>jama.rw</domain:name>
      </domain:info>
    </info>
    <clTRID>5dd409b369d38</clTRID>
  </command>
</epp>

-----END-----2019-11-19 16:26:43-----

-----READ-----2019-11-19 16:26:43-----
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
  <response>
    <result code="2202">
      <msg>Invalid authorization information; Incorrect Authcode provided.</msg>
    </result>
    <trID>
      <clTRID>5dd409b369d38</clTRID>
      <svTRID>1574177203492</svTRID>
    </trID>
  </response>
</epp>

-----END-----2019-11-19 16:26:43-----`

**Comment by metaregistrar** [comment]
This XML is not well readable via Github. Can you send it to ewout@metaregistrar.com?

**Comment by mrclick** [comment]
Already Sent!.

**Comment by mrclick** [comment]
Issue resolved!
Any one facing the same issue, In my case this was caused by an IP restriction.

**Comment by Xsmael** [comment]
> Issue resolved! Any one facing the same issue, In my case this was caused by an IP restriction.

But how did you solve it ? on which side was the restriction ?
