### ISSUE TITLE
Problems with = in password in settings.ini

### ISSUE THREAD

**Issue by kg00** [metaregistrar/php-epp-client#24]
Hi,
If there is an '=' in a password (or any other param in settings.ini), loadSettings will load only the part before the '='

If you add limit 2 to explode, this will be solved:

File: Protocols/EPP/eppConnection.php
Line: 913  

Change: 
        list($param, $value) = explode('=', $setting);
To:
        list($param, $value) = explode('=', $setting,2);

Thank you
//

**Comment by metaregistrar** [comment]
You solution has been implemented, thanks for the contribution

**Comment by kg00** [comment]
There are 2 more places to change in the same file:
Line 150 and line 885

Thank you

**Comment by metaregistrar** [comment]
Your issue has been resolved, the lines are changed.
