### ISSUE TITLE
Invalid contact type: reseller

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#242]
Hey Guys,

I noticed that I am getting an error when doing a domain info command: Invalid contact type: reseller

It looks like there is a reseller contact defined, but it crashes the EPP class...
How can I go about ignoring it or getting it to not throw the "Invalid contact type: reseller" error?

Kind Regards

**Comment by metaregistrar** [comment]
Which extensions are you using?

**Comment by swartjie** [comment]
It's for the co.za extension

**Comment by metaregistrar** [comment]
I will check domain:info with co.za to see where it goes wrong.

**Comment by swartjie** [comment]
As a side note, it does not always happen. It only happens when a contact type is spesified as a reseller contact instead of admin, tech or billing for example...
Then it throws the error. Hope it helps :)

**Comment by metaregistrar** [comment]
We don't have any co.za contacts with reseller info in it... can you give me the file name and line number of the crash?

**Comment by metaregistrar** [comment]
I think i found it, and fixed it in the latest commit

The system did not accept this type of contact:
 <domain:contact type="reseller">resellercontact</domain:contact>

Now it does.
