### ISSUE TITLE
iis:deleteNotify con:delete not recognised

### ISSUE THREAD

**Issue by QubeX2** [metaregistrar/php-epp-client#246]
->getMessage returns ''

This xml message is not recognized:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
    <response>
        <result code="1301">
            <msg>Command completed successfully; ack to dequeue</msg>
        </result>
        <msgQ id="3118904" count="225">
            <qDate>2019-12-24T02:00:08.0Z</qDate>
            <msg lang="en">   </msg>
        </msgQ>
<resData xmlns="urn:ietf:params:xml:ns:epp-1.0">
    <iis:deleteNotify xmlns:iis="urn:se:iis:xml:epp:iis-1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:se:iis:xml:epp:iis-1.2 iis-1.2.xsd">
        <con:delete xmlns:con="urn:ietf:params:xml:ns:contact-1.0">
            <con:id>cenedi8426-00001</con:id>
        </con:delete>
    </iis:deleteNotify>
</resData>
        <trID>
            <clTRID>5e7863f20a3b7</clTRID>
            <svTRID>593968690</svTRID>
        </trID>
    </response>
</epp>`

**Comment by metaregistrar** [comment]
If you want the message to be recognized, you will probably have to extend the IIS.SE code that is located in https://github.com/metaregistrar/php-epp-client/tree/master/Protocols/EPP/eppExtensions/iis-1.2

This package relies heavily on the contributions of users using the package and fixing problems. If you have fixed this, thank you for creating a pull request with the fix.
