### ISSUE TITLE
Shouldn't this be `include` instead of `require` since it is a private file?

### ISSUE THREAD

**Issue by lidakaml** [metaregistrar/php-epp-client#248]
Shouldn't this be `include` instead of `require` since it is a private file?
Or better yet, You can `require` this file if `testsetup.ini` has a parameter like:
`requireVendorAutoload = true` - make the file optional.

https://github.com/metaregistrar/php-epp-client/blob/ff93be65b8b51ee7505c4527a9e0ff972f29588e/Tests/eppTestCase.php#L2

**Comment by metaregistrar** [comment]
The difference between require() and include() is the type of error that is thrown in the case that the file is not found.

In all cases, if the file is not found, this eppTestCase.php will not work, so the .php file that is included or required MUST be present. When the file is present, there is no difference between require and include.
