### ISSUE TITLE
setForcehostattr in dnsbeEppCreateDomainRequest

### ISSUE THREAD

**Issue by xelmido** [metaregistrar/php-epp-client#252]
in `dnsbeEppCreateDomainRequest` class you do a setForcehostattr(true). But that doesn't seem to work.

It comes before the `parent::__construct($createinfo)`. So it would be overwritten. Tried to put it after the parent, still no luck. I can't figure out why this is. When you pass true in the construct as 2nd parameter as you do with the `euridEppCreateDomainRequest` it will work.

**Comment by metaregistrar** [comment]
You are correct, is have modified the parent::__contstruct() to include the correct hostattr switch.

```
parent::__construct($createinfo, $this->getForcehostattr());
```
