### ISSUE TITLE
About the certification path

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#253]
Generally, the absolute path of the SSL certificate stored in the development environment and the production environment is different, but the relative path is the same. In the current version, the SSL certificate path is stored in the local configuration file. When using eppConnection :: create (), it cannot be dynamically converted to the absolute path of the environment according to the operating environment.

**Comment by metaregistrar** [comment]
There is also an API call to add a SSL certificate. The INI file is just for convenience. 

In Development / Production environments I would always recommend to use the API calls to connect, not the INI files.

```
public function enableCertification($certificatepath, $certificatepassword, $selfsigned = false) {
        $this->local_cert_path = $certificatepath;
        $this->local_cert_pwd = $certificatepassword;
        $this->allow_self_signed = $selfsigned;
    }
```
