### ISSUE TITLE
About log time zone setting

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#254]
In eppConnection :: enableLogging (), the time zone is forced to "Europe / Amsterdam", which is very unfriendly to developers in other countries. It is recommended to use UTC or allow developers to manually modify the time zone.

**Comment by metaregistrar** [comment]
ABSOLUTELY. Since UTC is used by almost all servers that perform domain name tasks using UTC makes it easier to compare.

I have removed this timezone setting from the latest dev version
