### ISSUE TITLE
Problems connecting to a server that requires a CA certificate

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#256]
When I use this project to connect to the real-name VSP server, I encountered a VSP server that uses a self-signed certificate and needs to submit a CA certificate to properly connect to the server, but currently only local_cert is used in the project, and cafile is not used. So can you add this configuration to the project?

**Comment by metaregistrar** [comment]
That depends on what is needed to add it. If you can program it yourself and create a pull request, i will be happy to add that to the repository.

So far, we have used this code to connect to 40+ different registries, including the big ones like Verisign, and this code works in all those cases.

For the registries that use a signed key, i always put all the key information (root key, registry key, signed key) into one file, and use that for the connection, it works.

**Comment by jansen-s** [comment]
Thanks for your suggestion, putting the contents of the private key, certificate, and CA in one file solved my problem.
