### ISSUE TITLE
registerdomain response object

### ISSUE THREAD

**Issue by kg00** [metaregistrar/php-epp-client#26]
Testing to register iis domain. 

In Example/registerdomain.php in function createdomain the test for the response when creating domain is if it is instance of eppCreateResponse:

`if ((($response = $this->eppconn->writeandread($create)) instanceof Metaregistrar\EPP\eppCreateResponse) && ($response->Success())) {`

But when checking the response, the object returned is eppCreateDomainResponse
So changing to:

`if ((($response = $this->eppconn->writeandread($create)) instanceof Metaregistrar\EPP\eppCreateDomainResponse) && ($response->Success())) {`

makes it work, but is this really correct?

**Comment by metaregistrar** [comment]
Hi,

We once used to work with eppCreateResponse for domain, contact and host creates, but later on decided that it would be better to split the functionality into multiple classes. We seem to have missed fixing this example accordingly. This is fixed in the latest push.
