### ISSUE TITLE
eppContact __construct bug

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#260]
In the construction method of eppContact __construct, setPassword was called twice, which caused the incoming password to be overwritten。
In addition, in the construction method, it is not possible to generate a password by default, otherwise, when updating, it will be considered to update authInfo and submit a wrong request。

**Comment by metaregistrar** [comment]
And I was sure that absolutely no-one uses epp contact passwords. Anyway, the bug has been fixed.

**Comment by jansen-s** [comment]
I have seen you fix this BUG, but your fix is wrong, which will cause the password update to be submitted when updating the contact. The correct fix is as follows:
```
        if ($postalInfo instanceof eppContactPostalInfo) {
            $this->addPostalInfo($postalInfo);
        } else {
            if (is_array($postalInfo)) {
                foreach ($postalInfo as $pi) {
                    if ($pi instanceof eppContactPostalInfo) {
                        $this->addPostalInfo($pi);
                    }
                }
            }
        }
        $this->setId($this->generateContactId());
        $this->setEmail($email);
        $this->setPassword($password);
        $this->setVoice($voice);
        $this->setFax($fax);
        $this->setStatus($status);
```
