### ISSUE TITLE
fwrite cannot write big data

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#263]
When accessing Teleinfo real-name verification, I found that my local environment can only upload 97Kb. After debugging, I found that the number of bytes written by fwrite in a single time is less than the number of bytes that need to be sent. In order to send all the data completely, I need to call fwrite in a loop .

**Comment by jansen-s** [comment]
In the PHP language reference document, fwrite has a NOTE and gives a piece of code, "Writing to a network stream may end before the whole string is written. Return value of fwrite () may be checked", the following code is given by NOTE :
```
<?php
function fwrite_stream($fp, $string) {
    for ($written = 0; $written < strlen($string); $written += $fwrite) {
        $fwrite = fwrite($fp, substr($string, $written));
        if ($fwrite === false) {
            return $written;
        }
    }
    return $written;
}
?>
```

**Comment by metaregistrar** [comment]
I can write this for you, but i have no means to test it, since i do not have any registry connections requiring large amounts of data. It is best if you write and test it yourself, and issue a pull request when it works so it can be incorporated in the source code.

**Comment by jansen-s** [comment]
After I set stream_set_blocking in connect () to true, the problem is solved and big data can be sent.

**Comment by metaregistrar** [comment]
I have added the function $conn->setBlocking(true); so that you can enable stream_set_blocking if you need to. The default value is 'false' so that existing users are not affected.
