### ISSUE TITLE
eppUpdateContactRequest's mothod "addContactChanges" bug

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#264]
The setOrganisationName method in eppContactPostalInfo uses the htmlspecialchars function to convert the value. When the parameter value passed in by the htmlspecialchars function is null, htmlspecialchars will return an empty string. When updating contact information, __construct defaults to null. In the addContactChanges method of eppUpdateContactRequest When determining whether the organization needs to be updated, the is_null function is used, which causes the library to think that the organization information needs to be updated, but the actual organization name submitted is an empty string, so the registry will report an error. Here the judgment of addContactChanges method of eppUpdateContactRequest should be modified to "$ postal-> getOrganisationName ()> 0"

**Comment by metaregistrar** [comment]
The problems have been fixed for the OrganisationName field and the other fields that use htmlspecialchars.
