### ISSUE TITLE
Factory instead => have to include params file

### ISSUE THREAD

**Issue by kg00** [metaregistrar/php-epp-client#27]
Hi
When using the new  factory instead of creating object, we have to include the path to config/settings file. Is this a deliberate change? I liked it better not having to include the path everywhere since it made it easier to handle changes in path later on.

Earlier (and as it is still in __construct) the default was to use settings.ini in the actual folder (Registries/iisEppConnection in our test case), but now we get "File not found" when trying to use :

`if ($this->eppconn = Metaregistrar\EPP\iisEppConnection::create('')) {`

if we do not include the path to the file.

Is this something you will change to not having to include it in the create call so it works as earlier?

Thank you

**Comment by kg00** [comment]
Just to update, even if I enter the correct path to the settings.ini -file in the call on create, it will not work. I get "ERROR: Error writing content " (and it seems the destruction of the connections is not done)

**Comment by metaregistrar** [comment]
You do not have to use the new factory, it is still possible to create connections the 'old' way. 

Please note that for an iisEppConnection you will also need a valid certificate file.

My settings.ini looks like this:
hostname=epp.iis.se
port=700
userid=xxxxxxxxx
password=xxxxx
certificatefile=xxxxxx.pem
certificatepassword=xxxxxxx

**Comment by kg00** [comment]
The old one works fine.
But when using the factory, it does not work. It gives error at login for some odd reason (writing error).

We do use certificates and the old connection works fine and we can create contacts, domains etc.

**Comment by metaregistrar** [comment]
Ok, i shall test old and new way of connecting and fix the issues there.

**Comment by metaregistrar** [comment]
I have fixed your problem.
In the settings.ini you can specify a certificate path.

if there is no / or \ in the certificate path, the system will assume the cerificate file is in Registries/iisEppConnection

If you specify a full path in the certificate path, so you can store your certificate in a safe location, then the path to Registries/iisEppConnection is not added to the path.

So my recommendations:
- Use the ::create factory to create the connection
- Specify the full certificate path in the ini file.
