### ISSUE TITLE
Help me understand the poll

### ISSUE THREAD

**Issue by sayoki** [metaregistrar/php-epp-client#275]
I want to read data out my poll response:

Original:
"""<?xml version="1.0" encoding="UTF-8" standalone="no"?>
   <epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
     <response>
       <result code="1301">
         <msg>Command completed successfully; ack to dequeue</msg>
       </result>
       <msgQ count="5" id="12345">
         <qDate>2000-06-08T22:00:00.0Z</qDate>
         <msg>Transfer requested.</msg>
       </msgQ>
       <resData>
         <obj:trnData
          xmlns:obj="urn:ietf:params:xml:ns:obj-1.0">
           <obj:name>example.com</obj:name>
           <obj:trStatus>pending</obj:trStatus>
           <obj:reID>ClientX</obj:reID>
           <obj:reDate>2000-06-08T22:00:00.0Z</obj:reDate>
           <obj:acID>ClientY</obj:acID>
           <obj:acDate>2000-06-13T22:00:00.0Z</obj:acDate>
           <obj:exDate>2002-09-08T22:00:00.0Z</obj:exDate>
         </obj:trnData>
       </resData>
       <trID>
         <clTRID>ABC-12345</clTRID>
         <svTRID>54321-XYZ</svTRID>
       </trID>
     </response>
   </epp>"""

My .BE registrar:
"""<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:dnsbe="http://www.dns.be/xml/epp/dnsbe-1.0">
  <response>
    <result code="1301">
      <msg>Command completed successfully; ack to dequeue</msg>
    </result>
    <msgQ count="2" id="3714705">
      <qDate>2020-06-01T19:01:39.214Z</qDate>
      <msg>Transfer of domain name completed</msg>
    </msgQ>
    <resData>
      <dnsbe:pollRes>
        <dnsbe:action>AWAY</dnsbe:action>
        <dnsbe:domainname>mydomain.be</dnsbe:domainname>
        <dnsbe:returncode>1000</dnsbe:returncode>
        <dnsbe:type>TRANSFER</dnsbe:type>
      </dnsbe:pollRes>
    </resData>
    <trID>
      <clTRID>5ee23952b487d</clTRID>
      <svTRID>dnsbe-0</svTRID>
    </trID>
  </response>
</epp>"""

I want to read the domainname.

I have no idea how to understand reading this and tried to rewrite the function getDomainName.

    public function getDomainName() {
		#return $this->queryPath('/epp:epp/epp:response/epp:resData/domain:'.$this->messageType.'Data/domain:name');
        return $this->queryPath('/epp:epp/epp:response/epp:resData/epp:dnsbe');
    }

Sadly i am stuck.

**Comment by metaregistrar** [comment]
Please when you add EPP response to this issue, use the triple-quote so that the structure is visible

Like this:
```
This is code
```

**Comment by sayoki** [comment]
like this?

**Comment by sayoki** [comment]
`    public function getDomainName() {
		#return $this->queryPath('/epp:epp/epp:response/epp:resData/domain:'.$this->messageType.'Data/domain:name');
        return $this->queryPath('/epp:epp/epp:response/epp:resData/dnsbe:pollRes/dnsbe:domainname');
    }`

I managed to get the domainname.
