### ISSUE TITLE
DOMXPath::query() PHP warnings on 2001 errors

### ISSUE THREAD

**Issue by davey013** [metaregistrar/php-epp-client#277]
I'm getting two PHP warnings, I think this only happens when I'm receiving a 2001 error in the response. In my case I'm trying to create a new contact in SIDN, with only empty values which is triggering the 2001 error, followed by the following PHP warnings:

`Warning: DOMXPath::query(): Undefined namespace prefix in xxxxxx/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppResponses/eppResponse.php on line 384`

`Warning DOMXPath::query(): Invalid expression in xxxxxx/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppResponses/eppResponse.php on line 384`

**Comment by metaregistrar** [comment]
This can only happen if you have not defined the correct extensions for SIDN. 

Have you created an sidnEppConnection instead of an eppConnection for this request?

**Comment by davey-w** [comment]
Yes, I'm creating an sidnEppConnection:

```
use Metaregistrar\EPP\sidnEppConnection;
use Metaregistrar\EPP\sidnEppCreateContactRequest;
use Metaregistrar\EPP\eppContactPostalInfo;
use Metaregistrar\EPP\eppContact;

$conn = new sidnEppConnection();
$conn->setHostname(xxxxxx); 
$conn->setPort(xxxxxx); 
$conn->setUsername(xxxxxx);
$conn->setPassword(xxxxxx);
$conn->login();

$address = new eppContactPostalInfo($name, $city, $country, $organisation, $street, '', $zipcode, eppContact::TYPE_LOC);

$contactinfo = new eppContact($address ,$email, $phone);
$contact = new sidnEppCreateContactRequest($contactinfo);

if ($response = $conn->request($contact)) {

}
```
