### ISSUE TITLE
Traficom/Ficora failing

### ISSUE THREAD

**Issue by NikoGrano** [metaregistrar/php-epp-client#283]
Gets stuck. Cannot get any futher errors. Rel #268 

Working fine with https://github.com/FinnishTechCompany/php-epp-client.

**Comment by NikoGrano** [comment]
No resolution to this...? @metaregistrar

**Comment by metaregistrar** [comment]
Hi Niko,

php-epp-client is an open-source product. The Ficora connection was not
developed by us, but by one of the users of the product. We do not have a
direct connection to Ficora to test or debug this addittion.


Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar BV


Op di 31 aug. 2021 om 09:49 schreef Niko Granö ***@***.***>:

**Comment by NikoGrano** [comment]
As referenced ,there is working fork of this, but Im unable to port it to currently working version of this library. 
Ficora provides open test environment to anybody to use: https://epptest.ficora.fi/s/en
This site includes all contract information to tech support.
