### ISSUE TITLE
message: "No valid response class found for request class Metaregistrar\EPP\metaregEppTransferExtendedRequest"

### ISSUE THREAD

**Issue by Jeroenhulshof** [metaregistrar/php-epp-client#284]
transferDomain gives me this error. 

```
        $eppDomain = new eppDomain('domain.nl');
        $eppDomain->setAuthorisationCode('authcode');
        $eppDomain->setRegistrant('registrant');

        $eppDomain->addContact(new \Metaregistrar\EPP\eppContactHandle('contact', \Metaregistrar\EPP\eppContactHandle::CONTACT_TYPE_ADMIN));
        $eppDomain->addContact(new \Metaregistrar\EPP\eppContactHandle('admin', \Metaregistrar\EPP\eppContactHandle::CONTACT_TYPE_TECH));
        $eppDomain->addContact(new \Metaregistrar\EPP\eppContactHandle('tech', \Metaregistrar\EPP\eppContactHandle::CONTACT_TYPE_BILLING));

        $transfer = new metaregEppTransferExtendedRequest(eppTransferRequest::OPERATION_REQUEST, $eppDomain);
        if ($response = $this->sidnConn->request($transfer)) {
            /* @var $response Metaregistrar\EPP\eppTransferResponse */
            echo $response->getDomainName(),"transfer request was succesful\n";
        }
```

note: I edited out the handles and auth code for obvious reasons.

What am i doing wrong here?

**Comment by metaregistrar** [comment]
Hi Jeroen,

For this connection, did you create an 'eppConnection' or a 'metaregEppConnection'

You have to create the last one, as it will make sure that all classes and responses are loaded and in place before you use them.

**Comment by Jeroenhulshof** [comment]
Hi Metaregistrar, 

Thanks for the quick reply.

I have an sidnEppConnection set up and is working fine for creating domains etc, but not for transferring domains.

**Comment by Jeroenhulshof** [comment]
I think i need more coffee. Ofcourse i cannot use metaReg attributes since i'm using sidnEppConnection. I've changed this line: 

`$transfer = new metaregEppTransferExtendedRequest(eppTransferRequest::OPERATION_REQUEST, $eppDomain)`

to 

$transfer = new eppTransferRequest(eppTransferRequest::OPERATION_REQUEST, $eppDomain);

And it all works as expected. Sorry for opening this issue, it can be deleted or closed.
