### ISSUE TITLE
Can't add host to domainTransfer?

### ISSUE THREAD

**Issue by Jeroenhulshof** [metaregistrar/php-epp-client#286]
Hi, 

I'm trying to add a host to domains that are being transferred through the EPP Api. For some reason, the host is not added when the transfer is completed. Ofcourse, host is just a placeholder for the original host.

`$eppDomain->addHost(new \Metaregistrar\EPP\eppHost('host'));`

**Comment by metaregistrar** [comment]
Many registries do not support adding hosts to a transfer command. When you want to switch nameservers, first transfer the domain name, then set the nameservers.

There are registrars that will support adding nameservers, but in their back-end they will do for you what is stated above: First they will transfer the domain name, then set the nameservers.
