### ISSUE TITLE
Issue with createContact request (SIDN)

### ISSUE THREAD

**Issue by nalletje** [metaregistrar/php-epp-client#292]
We found a issue with the createContact request for SIDN.

On creating a new contact it returns
"**2001: Command syntax error**"

The reason for this is, the XML is invalid. We do not provide any password for the client by:
`$contact->setPassword(null);`

But what this piece of code also does, is removing this in the request XML:
`<contact:authInfo>
          <contact:pw/>
        </contact:authInfo>`

However every provider ignores the contact password, they still want to see this piece of xml...

We fixed it for ourselve by overwritten the function **setPassword** (114) in Protocols/EPP/eppRequests/eppCreateContactRequest

**Original**
`public function setPassword($password) {`
       `if (!is_null($password))`
        `{`
            `$authinfo = $this->createElement('contact:authInfo');`
            `$authinfo->appendChild($this->createElement('contact:pw', $password));`
           ` $this->contactobject->appendChild($authinfo);`
        `}`
    `}`

**We overwrited it with**
`public function setPassword($password) {`
            `$authinfo = $this->createElement('contact:authInfo');`
            `$authinfo->appendChild($this->createElement('contact:pw', $password));`
            `$this->contactobject->appendChild($authinfo);`
    `}`

It would be awesome if we would have an option to allow this empty in the xml

**Comment by metaregistrar** [comment]
You can easily have an empty password by using setPassword("");

In this case the password is not null, so it will be set as an empty string.

**Comment by nalletje** [comment]
@metaregistrar If we use
`$contact->setPassword('');`

we got the same results. it is stripped from the XML

**Comment by nalletje** [comment]
@metaregistrar 

Let me redraw that. This is weird, but it seems to work:


**If we do this, it gets stripped from the XML:**
$contact = new eppContact(
            new eppContactPostalInfo(
                $domeinContact->naam,
                $domeinContact->plaatsnaam,
                $domeinContact->land->iso2,
                $domeinContact->bedrijfsnaam,
                $domeinContact->adres,
                $domeinContact->staat_of_provincie,
                str_replace(' ','', $domeinContact->postcode),
                eppContact::TYPE_LOC
            ),
            $domeinContact->email,
            $domeinContact->telefoon
        );
        $contact->setPassword('');


**If we do this, it seems to work**
$contact = new eppContact(
            new eppContactPostalInfo(
                $domeinContact->naam,
                $domeinContact->plaatsnaam,
                $domeinContact->land->iso2,
                $domeinContact->bedrijfsnaam,
                $domeinContact->adres,
                $domeinContact->staat_of_provincie,
                str_replace(' ','', $domeinContact->postcode),
                eppContact::TYPE_LOC
            ),
            $domeinContact->email,
            $domeinContact->telefoon,
            null,
            ''
        );
(Last '', is password)
