### ISSUE TITLE
Changing The AuthCode (EPP Key / Password)

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#295]
Hey guys,

Can someone please advise me how to use this class to change the EPP key for a domain?
If possible to query it back, but I mainly need to be able to update it....

I am having a bit of a hard time getting an example of how to do that...

Thank you :)

**Comment by metaregistrar** [comment]
https://github.com/metaregistrar/php-epp-client/blob/master/Examples/changepassword.php

**Comment by swartjie** [comment]
> https://github.com/metaregistrar/php-epp-client/blob/master/Examples/changepassword.php

Hey bud, Correct me if I am wrong, but that is not to change the domain's EPP password/key?
The domain's not mentioned, or instance there off created, It looks like that function is changing the connection's password or something of the like?

Please correct me if I am wrong though :)

**Comment by swartjie** [comment]
As a side note. 1 thing I noticed is the exact code worked with ZACR as the registry and the .net.za domains, but did not work with Registry Africa (who'm I believe both have the exact same EPP servers, But not 100% sure)

**Comment by metaregistrar** [comment]
Ah - sorry I misread your question.

Standard, the EPP implementation does not allow for change of authcode for a domain name. That means, every registry that allows it has implemented it in their own way. The code to do this must be found or must be added to the appropriate extension in Protocol/EPP/eppExtensions

**Comment by swartjie** [comment]
> Ah - sorry I misread your question.
> 
> Standard, the EPP implementation does not allow for change of authcode for a domain name. That means, every registry that allows it has implemented it in their own way. The code to do this must be found or must be added to the appropriate extension in Protocol/EPP/eppExtensions

How does one go about doing this?
Do you have some form of an example?
