### ISSUE TITLE
Premium Domain Checks Failing

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#296]
Hey Guys,

I think I am running into a bug.
When I try to perform a premium check with the code below, I am running into an error `Error: Call to undefined method Metaregistrar\EPP\eppCheckDomainResponse::getChargeForDomainName()` can you please help me understand why? Is it something I am missing?

I got the code from you guys on the forum a couple months back, So I'm pretty sure it should work but seems not too... I'm hoping you see something I may be missing?

Code:

**Parent Function Line Being Called:**
`$prem_domain_check = $epp->premiumcheck($params['original']['sld'].$tld);`

**Premium Check Function Bein Called**
```
function premiumcheck($domainname) {
        $this->login();
        $check = new eppCheckDomainRequest(new eppDomain($domainname));
        
        if ($response = $this->conn->request($check)) {
            /* @var $response chargeEppCheckDomainResponse */
            //echo $response->saveXML(); echo "<br>";
            $this->logout();
            return $response->getChargeForDomainName($domainname);
            //$response->getElementsByTagName('')
        } else {
            echo "ERROR2\n";
        }
        
        $this->logout();
        return null;
    }
```

Any advise would be highly appreciated :)

**Comment by metaregistrar** [comment]
If a function is missing, it is probably because you are missing an extension.

Use the function $conn->addExtension("xxxxxx") to add an extension to a connection, the list of possible extensions can be found in https://github.com/metaregistrar/php-epp-client/tree/master/Protocols/EPP/eppExtensions

Probably the fee-1.0 or fee-0.23 that you are missing, but i'm not sure, I have never used these extensions.

**Comment by swartjie** [comment]
> If a function is missing, it is probably because you are missing an extension.
> 
> Use the function $conn->addExtension("xxxxxx") to add an extension to a connection, the list of possible extensions can be found in https://github.com/metaregistrar/php-epp-client/tree/master/Protocols/EPP/eppExtensions
> 
> Probably the fee-1.0 or fee-0.23 that you are missing, but i'm not sure, I have never used these extensions.

Correct me if I am wrong, but the error `Error: Call to undefined method Metaregistrar\EPP\eppCheckDomainResponse::getChargeForDomainName()` means a function is not included (maybe a missing `use`), not an extension that's missing in the XML builder?

**Comment by rugambafri** [comment]
> getChargeForDomainName

But for me, if i use addExtension the registry return code 2004

**Comment by metaregistrar** [comment]
It is possible that this extension was not properly tested. This repository relies heavily on the contributions of its users, so if you find an error, please debug it and use a pull request to get the fixed code into the repo
