### ISSUE TITLE
EPP Connection Error SSL Error

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#297]
Hey Guys,

I have been using your class for a while with success, but all of the sudden, I can't anymore...
When I try to connect now with the code below, I keep getting the error below.

I know this error is related to SSL settings. But what's strange is, that the certificate works 100% on my other server, but on my local pc it doesn't... So I suspect there's a requirement that my PC does not have that the server obviously does?

Connection:

```
       $this->conn = new \Metaregistrar\EPP\eppConnection(TRUE);
        $this->conn->setLogFile(storage_path('logs/epp.log'));
        $this->conn->setHostname($this->host); // Hostname may vary depending on the registry selected
        $this->conn->setPort($this->port); // Port may vary depending on the registry selected
        $this->conn->setUsername($this->username);
        $this->conn->setPassword($this->password);
        $this->conn->setVerifyPeerName(false);
        $this->conn->setVerifyPeer(false);
        
        $this->conn->enableCertification($this->certificate, '');
        
        $this->conn->login();
```

Error (when host is `epp.coza.net.za`): `Packet size is too big: 352518908. Closing connection`
Error (when host is `ssl://epp.coza.net.za`): `stream_socket_client(): Unable to set local cert chain file `/var/www/html/infinite/epp.pem'; Check that your cafile/capath settings include details of your certificate and its issuer`

The same certificate is used, and i've even generated another but it runs into the same problem?

**### _Side Note:_**
My thought aswell was that my IP kept changing or had some sort of NAT problem due to it being a home network, So I did setup a VPN to run the traffic through my own VPN, but that did not help resolve the issue either, Got the exact same problem :(

Any assistance would be much appreciated :)

Thanks Guys

**Comment by metaregistrar** [comment]
Error (when host is ssl://epp.coza.net.za): stream_socket_client(): Unable to set local cert chain file /var/www/html/infinite/epp.pem'; Check that your cafile/capath settings include details of your certificate and its issuer`
- Are you sure this certficate file is present and readable on your machine? That the file contains the right certficate?


Error (when host is epp.coza.net.za): Packet size is too big: 352518908. Closing connection
- Packet size too big is common when SSL is expected but not in the configuration. The encrypted data indicated a packet size that is way bigger than the system can handle

Summarizing, I would keep the ssl://epp.coza.net.za in the configuration, because it is correct, and concentrate on the warning that the certificate file is not settable.

**Comment by swartjie** [comment]
> Error (when host is ssl://epp.coza.net.za): stream_socket_client(): Unable to set local cert chain file /var/www/html/infinite/epp.pem'; Check that your cafile/capath settings include details of your certificate and its issuer`
> 
> * Are you sure this certficate file is present and readable on your machine? That the file contains the right certficate?

The file is present and accessible. I've tried connecting with command line and succeeded. is there a spesific permission that the library requires the file to have?

as a note on that, I did read the file with the script and var_dumped the content, and it was able to open the file successfully.
Also the SSL is correct since it works on our other server... It may be a permissions issue. But the user does have access to the file. Should the permissions rather be set to sudo or what would you recommend?

**Comment by swartjie** [comment]
> Error (when host is ssl://epp.coza.net.za): stream_socket_client(): Unable to set local cert chain file /var/www/html/infinite/epp.pem'; Check that your cafile/capath settings include details of your certificate and its issuer`
> 
> * Are you sure this certficate file is present and readable on your machine? That the file contains the right certficate?
> 
> Error (when host is epp.coza.net.za): Packet size is too big: 352518908. Closing connection
> 
> * Packet size too big is common when SSL is expected but not in the configuration. The encrypted data indicated a packet size that is way bigger than the system can handle
> 
> Summarizing, I would keep the ssl://epp.coza.net.za in the configuration, because it is correct, and concentrate on the warning that the certificate file is not settable.

Hey bud, You were 100% right. Was a permissions issue on the certificate file itself. The php could for some reason read the file, but not use it... Was able to solve it though :)
