### ISSUE TITLE
Afilias EPP Connection

### ISSUE THREAD

**Issue by James4645** [metaregistrar/php-epp-client#298]
What would it take to add support for a connection for an Afilias TLD?

**Comment by metaregistrar** [comment]
Hi James,

The php-epp-client relies heavily on the contribution of users of the product. Basically, we encourage PHP programmers to write extensions to the library and add them using a pull request.

**Comment by James4645** [comment]
I get that. I just have no clue where to start as I know nothing about the EPP protocol.

**Comment by James4645** [comment]
So I take it then that there is no resource you can point to to allow me to get up to speed with whats needed.  And I'm guessing that there is no Afilias module currently that nobody who actually knows what they are doing has any need or desire to create this...thanks I will look into other projects then.
