### ISSUE TITLE
Urgent issue : Issue with supporting documents extension,

### ISSUE THREAD

**Issue by bavarianboy** [metaregistrar/php-epp-client#303]
When registering a reserved domain name or a special TLD, you are required to attach at least one supporting document

when i try to attach a file over 67 KB the server closes the connection, but if the file (base64 encoding) smaller than this value the request is made without problems, and domain created 

i have contacted the service provider and they told me that the allowed file size is up to 30 MB

The return message 
"message": "Unexpected closed connection by remote host..."

File attached for the XML for creating a domain name

[test-xml.TXT](https://github.com/metaregistrar/php-epp-client/files/6160357/test-xml.TXT)

**Comment by metaregistrar** [comment]
This extension of Saudinic was not written by us, and is not in the repository, therefore difficult to debug without code.
