### ISSUE TITLE
eurid Contact naturalPerson filed missing

### ISSUE THREAD

**Issue by f4810** [metaregistrar/php-epp-client#306]
Hi, in euridEppContact.php miss the ext field naturalPerson :

<contact-ext:naturalPerson>
Boolean element detailing whether or not a contact is a natural person.

Can have one of the following values:
◦ true if the contact is a natural person;
◦false if the contact is a company/undertaking or an organisation.

The element is mandatory for all contacts.

**Comment by metaregistrar** [comment]
Added code today to support this extension
