### ISSUE TITLE
Search for handles

### ISSUE THREAD

**Issue by DaveDrupsteen** [metaregistrar/php-epp-client#307]
Hi,

Is it possible to search for a handle (or multiple) based on some criteria such as name, address, email or such?
After looking through the code and such I cannot seem to find anything. But I am hoping I am wrong.

But besides that, this is great project it has helped us alot!

**Comment by stuarthaas-spark** [comment]
@DaveDrupsteen At least as far as I can tell, the only way to look up contacts is by the contact id and for domains it's by the domain name.

**Comment by metaregistrar** [comment]
When EPP was created, apparently nobody forsaw the need to search through domain names or contacts. The only way to check contacts is via the contact ID. You have to maintain your own tables with contact information.
