### ISSUE TITLE
eppCheckRequest

### ISSUE THREAD

**Issue by karborator** [metaregistrar/php-epp-client#31]
Hello , 
I'm trying to check availability of domain, following checkdomains.php example.
what should I pass to eppCheckRequest  at the construct ? 
when i do try :       $response = $this->checkdomains($conn, 'epptest.ficora.fi');
error message appears : "Error 2400: Command faile"
           
            $response = $this->checkdomains($conn, 'epptest.ficora.fi'');

When I pass eppDomain obj to checkdomains function , 
following err message appears: "Error 2005: Parameter value syntax error"

            $eppDoamin = new eppDomain('epptest.ficora.fi');
            $eppDoamin->setAuthorisationCode('*********');
            $response = $this->checkdomains($conn, $eppDoamin);

Interesting if I try to check "domain.fi" return "is taken" ( works )

Thanks

**Comment by metaregistrar** [comment]
You are checking a third-level domain name epptest.ficora.fi. That is not possible.

The domain name you have selected is not a domain name you can check. You can check ficora.fi. Or anynameyoucanthinkof.fi

But the domain name can only contain one dot. Not more.

**Comment by karborator** [comment]
Ok thanks :+1:
