### ISSUE TITLE
Keep Getting Packet Size To Big's

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#312]
Hey Guys,

I have been using the module for quite a while with great success... But I keep running into 1 problerm.

The ZACR OT&e server keeps rejecting my sessions... With the normal servers if we use ssl://hostname then it works. but with the OT&e server, if I use ssl://regphase3.dnservices.co.za it just plainly refuses to work. It gives me a connection error.

If I do remove the ssl:// then it opens the stream but I get a packet size to big error, even though I am using the certificate the registry provided for the connection...

My code below:

$this->conn = new Metaregistrar\EPP\cozaEppConnection(TRUE);
$this->conn->setHostname($this->host); // Hostname may vary depending on the registry selected
$this->conn->setPort($this->port); // Port may vary depending on the registry selected
$this->conn->setUsername($this->username);
$this->conn->setPassword($this->password);
$this->conn->setVerifyPeerName(false);
$this->conn->setVerifyPeer(false);
$this->conn->enableCertification($this->certificate['path'], $this->certificate['password'], true);
$this->conn->login();

The stream does open but then when the login command is sent I get "Packet size is too big: 352518396. Closing connection"

Any idea why i would be hitting this wall constantly?

**Comment by swartjie** [comment]
I have just received feedback that the ssl needs to be fully disabled. But even removing the 2nd last line, Still does not return anything other than the packet size error?
I'm a bit hopeless... Unless I'm not disabling ssl correctly?

**Comment by swartjie** [comment]
Just to clarify, I also miss-spoke. It's not the OT&e server that's the issue, it's the regphase3.dnservices.co.za server. The one that you need to verify with when you start the technical accreditation process...

**Comment by swartjie** [comment]
Hey guys, Ok so i've chatted with the registry. And SSL is definitely disabled for the regphase3. server.
And they've checked, even though I add  $this->conn->disableCertification(); to the metaregistrar instance it still tries to use ssl? Why would that be happening?

**Comment by swartjie** [comment]
Registry debug log:

03 Jun 2021 12:07:49,619 SID: ID: RAR:  DEBUG Connection accepted from da2.thathost.co.za/129.232.157.100 on port 53762
03 Jun 2021 12:07:49,621 SID:32B7D ID: RAR:  DEBUG Sending Greeting to 'EPP-#55-<rar>-32B7D-da2.thathost.co.za/129.232.157.100:3121'
03 Jun 2021 12:07:49,622 SID:32B7D ID: RAR:  WARN SSLException occurred while listening to 'da2.thathost.co.za/129.232.157.100': Connection has been shutdown: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

**Comment by metaregistrar** [comment]
If the registry does not use SSL for its OTE servers, you only have to set Hostname, Port, Username and Password. That should be enough to make connection.

The message "packet size too big" is mostly due to using SSL when the server does not, or using no SSL when the server needs it.

But in this case I would remove the $conn->EnableCertification line, because this will enable an SSL connection.

**Comment by swartjie** [comment]
I

> If the registry does not use SSL for its OTE servers, you only have to set Hostname, Port, Username and Password. That should be enough to make connection.
> 
> The message "packet size too big" is mostly due to using SSL when the server does not, or using no SSL when the server needs it.
> 
> But in this case I would remove the $conn->EnableCertification line, because this will enable an SSL connection.

I have removed that line. but I am still getting the packet size errors though?
How can we go about getting past this? The above shows there's still some form of ssl passed?

**Comment by swartjie** [comment]
According to the logs the connection is made. But when reading/writing the login, I am getting these errors...

**Comment by metaregistrar** [comment]
Can you enable logging and paste (a part) of the log from the php-epp-client?

**Comment by swartjie** [comment]
Do you mean the logging in the metaregistrar class?
Cause that only shows the connected to server, the attempt to write, and teh disconnect. Or is there an advanced debugging I can enable to show more?

**Comment by metaregistrar** [comment]
If you have the latest version, it shows with which settings, protocol and encryption it connects to the server - all valuable information.
