### ISSUE TITLE
InfoDomain: wrong xPath for eurid extensions

### ISSUE THREAD

**Issue by f4810** [metaregistrar/php-epp-client#313]
Hi, 
in file authInfo-1.1/eppResponses/euridEppInfoDomainResponse.php the functions **getQuarantined** and **getOnHold** have both a worng path. 

Must be something like:
'/epp:epp/epp:response/epp:extension/domain-ext:infData/domain-ext:quarantined'
and
'/epp:epp/epp:response/epp:extension/domain-ext:infData/domain-ext:onHold'

This is the actual response from eurid:
&lt;extension>
			&lt;domain-ext-2.3:infData>
				&lt;domain-ext-2.3:onHold>false&lt;/domain-ext-2.3:onHold>
				&lt;domain-ext-2.3:quarantined>true&lt;/domain-ext-2.3:quarantined>
				&lt;domain-ext-2.3:suspended>false&lt;/domain-ext-2.3:suspended>
				&lt;domain-ext-2.3:seized>false&lt;/domain-ext-2.3:seized>
				&lt;domain-ext-2.3:availableDate>2021-07-11T10:35:00.000Z&lt;/domain-ext-2.3:availableDate>
				&lt;domain-ext-2.3:deletionDate>2021-06-01T10:35:05.113Z&lt;/domain-ext-2.3:deletionDate>
...

**Comment by metaregistrar** [comment]
It seems that these functions should have a place in the domain-ext-2.3 extension, and not in de authInfo-1.1 extension.

**Comment by metaregistrar** [comment]
Added a commit today to address this issue.
