### ISSUE TITLE
Annotation in eppDomain class

### ISSUE THREAD

**Issue by Slisarenko** [metaregistrar/php-epp-client#314]
/**
     *
     * @param eppContact $registrant
     * @param string $authorisationCode
     */
    public function __construct($domainname, $registrant = null, $contacts = null, $hosts = null, $period = 0, $authorisationCode = null) {

        if (strlen($domainname)) {
            $this->setDomainname($domainname);
        } else {
            throw new eppException('Domain name not set');
        }
        $this->setPeriod($period);
        if ($registrant instanceof eppContact) {
            throw new eppException('Registrant must be Metaregistrar\EPP\eppContactHandle or string on eppDomain creation');
        }

As you can see the type of variable $registrant is eppContact, but If it is as stated in the annotation we throw an eppException, I think that you need to update an annotation. Personal for me, it's a problem because I'm getting an error from the psalm:
`expects Metaregistrar\EPP\eppContact|null, Metaregistrar\EPP\eppContactHandle provided`

**Comment by metaregistrar** [comment]
Fixed in the latest commit
