### ISSUE TITLE
The Command Tag not closed (Urgent Issue)

### ISSUE THREAD

**Issue by bavarianboy** [metaregistrar/php-epp-client#315]
I figured out that the command tag is not closed and also I tried to add an attribute for it but it's not accepted

I even opened the file eppRequests.php and update the getCommand() function by adding the extension but not appear on my code 

This is how the command display : 

[cide.TXT](https://github.com/metaregistrar/php-epp-client/files/6623876/cide.TXT)

File Attached

As you can see all the child tags goes outside the command tag

@

**Comment by metaregistrar** [comment]
This is not normal behaviour for this project. You must have called something special to get a result like this. Can you share your code?

**Comment by bavarianboy** [comment]
the point is the codes run without issues , but i got informed by the provider about this

Example : getting Domain Information

[Info Domain Example.txt](https://github.com/metaregistrar/php-epp-client/files/6740927/Info.Domain.Example.txt)

i got notified that this non closing take make issues on provider server specially on sending request with extension < the server closes the connection

[Create Domain XML.TXT](https://github.com/metaregistrar/php-epp-client/files/6740956/Create.Domain.XML.TXT)

**Comment by bavarianboy** [comment]
any updates regarding this

**Comment by metaregistrar** [comment]
As far as I can see from your Create Domain XML, modifications are made to the outgoing XML to accomodate Saudinic. I think that because of these modifications, the <command> tag is closed immediately

In your info Domain Example i cannot see how these modifications are created, so it is difficult to debug.
