### ISSUE TITLE
Link to Documentation

### ISSUE THREAD

**Issue by mritzmann** [metaregistrar/php-epp-client#316]
<img width="317" alt="Screenshot 2021-06-09 at 16 30 41" src="https://user-images.githubusercontent.com/4533780/121374248-09891200-c940-11eb-94c5-48c1e5bec7aa.png">

----

Link here on GitHub leads to a HTTP 404. Correct link would probably be:  
https://www.metaregistrar.com/docs/php-epp-client.html

**Comment by metaregistrar** [comment]
The link to the documentation is fixed
