### ISSUE TITLE
Class eppDnssecInfoDomainResponse not found in metaregInfoDomainResponse

### ISSUE THREAD

**Issue by mritzmann** [metaregistrar/php-epp-client#317]
Currently we use [nodepp](https://github.com/heytrav/nodepp), now we would like to test this library. But I do not get any result.

```shell
$ php checkdomain.php random-domain-34sfsgff23fwe.com
Checking 1 domain names

$ echo $?
255
````

The following appears in the php-error.log:

```shell
$ tail -f -n1 php-error.log 
[10-Jun-2021 11:09:12 Europe/Berlin] PHP Fatal error:  Class 'Metaregistrar\EPP\eppDnssecInfoDomainResponse' not found in /home/phpepp/php-epp-client/Protocols/EPP/eppExtensions/command-ext-1.0/eppResponses/metaregInfoDomainResponse.php on line 4
```

It should not be the firewall, because with `openssl s_client -quiet -connect eppltest1.metaregistrar.com:7000` i get a [greeting](https://gist.github.com/mritzmann/ea4f5bd442283c89a153125ebf9daea1) back. For ease of reference, I have included the installation and configuration below. What have I forgotten?

## Installation

I have installed php-epp-client as follows:

```shell
git clone https://github.com/metaregistrar/php-epp-client.git
cd php-epp-client

# settings
vi settings-meta.ini
cd Examples

# set path to config file
vi checkdomain.php
```

Set path to config file:

```diff
diff --git a/Examples/checkdomain.php b/Examples/checkdomain.php
index 53e0fe1..ca31f61 100644
--- a/Examples/checkdomain.php
+++ b/Examples/checkdomain.php
@@ -31,7 +31,7 @@ try {
     // userid=xxxxxxxx
     // password=xxxxxxxxx
     // Please enter the location of the file with these settings in the string location here under
-    if ($conn = eppConnection::create('')) {
+    if ($conn = eppConnection::create('../settings-meta.ini')) {
         // Connect and login to the EPP server
         if ($conn->login()) {
             // Check domain names
@@ -63,4 +63,4 @@ function checkdomains($conn, $domains) {
             echo "\n";
         }
     }
-}
\ No newline at end of file
+}
```

Settings:

```ini
$ cat settings-meta.ini 
interface=metaregEppConnection
hostname=ssl://eppltest1.metaregistrar.com
port=7000
userid=snowflake
password=**
```

**Comment by metaregistrar** [comment]
Hello,
Is this issue still open?

In checkdomain.php, the first lines are:
<?php
require('../autoloader.php');

This "require" statement should make sure that all the needed classes are loaded.

**Comment by mritzmann** [comment]
Hi @metaregistrar 

Thank you for your reply.

Did a `git pull` so I am up to date again. However, the problem is still present for me.

> In checkdomain.php, the first lines are:

Not quite sure what you mean by that.
