### ISSUE TITLE
Release for PHP8?

### ISSUE THREAD

**Issue by fermino** [metaregistrar/php-epp-client#322]
Hi! I noticed that lately there have been a few changes supporting PHP8. 
Is there any chance to release an official release?
If there's anything left to fix I'm willing to help!

Kind regards (and thanks for this great lib!)!

**Comment by metaregistrar** [comment]
I understand the question, but I am a bit hesitant to add php-8 specific functions to the repository.

Last few years, when adding functionality using PHP7, I received some questions from people using older PHP versions and not wanting to change the PHP setup only for this repo. The changes broke their code, and I myself am really not up to maintaining different versions for PHP 5.x, PHP 7.x and PHP 8.x

So at this moment 7.4 is the norm version, and the basic functionality of the repository will also work with 5.x. Not that I endorse this, but it is just how the real world works. Not everyone always uses the newest PHP versions.

**Comment by W0rma** [comment]
@metaregistrar I guess the question was not about adding PHP8 features to the code base but if you plan to tag a new release containing the changes which are _already_ in master. The latest tag 1.0.10 is about 19 months old.

**Comment by fermino** [comment]
Hi! @metaregistrar Yes, I totally get it!!

@W0rma @metaregistrar Indeed, I was only talking about making a new release with the changes that are already in master. In the commit https://github.com/metaregistrar/php-epp-client/commit/f6cd1ad1a23d04547e102f59681ec2909c3b0089 PHP8 was added as a compatible version, and it would be nice if those changes could be used directly from packagist.org!

Kind regards!
PS: Sorry if I wasn't super clear with it in the original issue!

**Comment by fermino** [comment]
This is with the only purpose of having a workaround for this: 

![image](https://user-images.githubusercontent.com/8203176/143583260-98cd51f0-b856-4644-8805-effca985c0d4.png)

**Comment by Hayajiro** [comment]
@metaregistrar Any chance to have this decision reconsidered? It's really not about adding PHP 8.0 features, but just a new tagged release that contains the respective commits required to use this library on PHP 8.0.

Given that PHP 8.0 has been out for over a year now, we'd really appreciate a new tagged release that supports PHP 8.0 (while keeping PHP 7.4 compatibility).

**Comment by fermino** [comment]
@metaregistrar thanks for the release!! :D

**Comment by metaregistrar** [comment]
Sorry it took so long ;-)
