### ISSUE TITLE
Duplicated class `euridEppInfoDomainResponse`

### ISSUE THREAD

**Issue by xelmido** [metaregistrar/php-epp-client#323]
Hi, 

Since a month you added a new class `euridEppInfoDomainResponse` to domain-ext-2.3. But it's still existing in authinfo-1.1 with the same namespace. 

https://github.com/metaregistrar/php-epp-client/commit/bc51615b9306fbe1655e52843926bde21edc3bcd#diff-9161d1d05dc8368e03051ecad5bf90c3629b7adedccbde58f1ddc23e098d7feb

What was the purpose of the new class (except for the new methods)?

**Comment by djurred** [comment]
Same issue `Cannot declare class Metaregistrar\EPP\euridEppInfoDomainResponse, because the name is already in use`

**Comment by metaregistrar** [comment]
Renamed the duplicate classes euridEppInfoDomainRequest en euridEppInfoDomainResponse to authEppInfoDomainRequest and authEppInfoDomainResponse
