### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by W0rma** [metaregistrar/php-epp-client#325]
Are there any plans to set up [Github Actions](https://docs.github.com/en/actions) in order to run the tests in the CI?
The CI could be easily configured in a way that it runs for every pull request.
It could execute the tests in different PHP version.

Would a PR adding a config file for Github Actions be accepted?

**Comment by metaregistrar** [comment]
We ourselves have no plans to use Github Actions, but contributions are always welcomed. This repo is very dependent on contributions from outside
