### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by karborator** [metaregistrar/php-epp-client#33]
Hi , 
I'm wondering how can I get a contact , some example if possible please.
Thanks

**Comment by metaregistrar** [comment]
To info a domain contact, you can use
 $info = new eppInfoContactRequest(new eppContactHandle($contactid));

If you then send that info to the registry, it will return all contact information for that $contactid

**Comment by karborator** [comment]
Thanks will test it :)

**Comment by karborator** [comment]
"objuri": null,
    "exturi": null,
    "xpathuri": {
      "urn:ietf:params:xml:ns:domain-1.0": "domain",
      "urn:ietf:params:xml:ns:contact-1.0": "contact",
      "urn:ietf:params:xml:ns:host-1.0": "host",
      "urn:ietf:params:xml:ns:epp-1.0": "epp"
    },
    "language": null,
    "version": null,
    "defaultnamespace": null,
    "publicnamespace": "urn:ietf:params:xml:ns:epp-1.0"

**Comment by metaregistrar** [comment]
I am not sure what you mean with this.

**Comment by karborator** [comment]
This was the response I got on  executing: 

            $conn = $this->getEppClient();
            $infoRequest = new eppInfoContactRequest(new eppContactHandle('#####'));
            infoContactResponse =  $conn->writeandread($infoRequest);

**Comment by metaregistrar** [comment]
Your request looks fine.

After that, you can do 

echo $infoContactResponse->saveXML(); 

to see the response from the registry.

To use the $infoContactResponse in your IDE, use
/* @var $infoContactResponse Metaregistrar\EPP\eppInfoContactResponse */

After this line your IDE knows how to handle the object and you can retrieve variables.

**Comment by karborator** [comment]
<?xml version="1.0" encoding="utf-8"?>
<epp xmlns:obj="urn:ietf:params:xml:ns:obj-1.0" xmlns="urn:ietf:params:xml:ns:epp-1.0">
    <response>
        <result code="2003">
            <msg>Required paramater missing</msg>
    
        </result>
        <trID></trID>
  
    </response>
</epp>

**Comment by metaregistrar** [comment]
In that case you need to review the manual and see what parameters they require.

If you want to know what you have sent to the registry, use
echo $info->saveXML();

This output you can compare with the example documentation of ficora.fi

**Comment by karborator** [comment]
Yes dis is from saveXML i forgot to say that

**Comment by karborator** [comment]
Interesting I got more xml if debug mode is activated

**Comment by karborator** [comment]
_<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0">
    <command>
        <info>
            <contact:info>
                <contact:id>#####</contact:id>
      
            </contact:info>
    
        </info>
        <clTRID>#######</clTRID>
  
    </command>
</epp>_

**Comment by metaregistrar** [comment]
I don't know the requirements of the registry - maybe they require an additional parameter?

**Comment by karborator** [comment]
I found this at some documentation.Idea how to implement it ? 

5 Contact Objects
5.1 Check
Based on RFC 5733.
Example request:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
 <command>
 <check>
 <contact:check
 xmlns: contact ="urn:ietf:params:xml:ns: contact -1.0">
 <contact:name>username1</contact:name>
 <contact:name>username2</contact:name>
 <contact:name>username3</contact:name>
 </contact:check>
 </check>
 <clTRID>ABC-12345</clTRID>
 </command>
</epp> 
```

**Comment by metaregistrar** [comment]
But that is a contact:check command you are referring to, not contact:info

A contact:check command goes like this:

$checkRequest = new eppCheckContactRequest(new eppContactHandle('#####'));

**Comment by karborator** [comment]
Checkout again , I'v edit the last post , 
Thanks

**Comment by karborator** [comment]
Hello , I just found out that I should provice authInfo , but want to ask how to set to the request info ? 
Example 
```
     <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
 <command>
 <info>
 <contact:info xmlns:contact="urn:ietf:params:xml:ns:contact-1.0">
 <contact:id>sh8013</contact:id>
 <contact:authInfo>
 <contact:pw>2fooBAR</contact:pw>
 </contact:authInfo>
 </contact:info>
 </info>
 <clTRID>ABC-12345</clTRID>
 </command>
</epp>
```


Currently 


        $conn = $this->getEppClient();
            $infoRequest = new eppInfoContactRequest(new eppContactHandle('XXXX'));
            $infoContactResponse = $conn->writeandread($infoRequest);
            echo $infoRequest->saveXML();
            exit;
    
```
         <?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:domain="urn:ietf:params:xml:ns:domain-1.0" xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xmlns:host="urn:ietf:params:xml:ns:host-1.0">
    <command>
        <info>
            <contact:info>
                <contact:id>XXXX</contact:id>
            </contact:info>
        </info>
        <clTRID>XXXXX</clTRID>
    </command>
</epp>

```

**Comment by metaregistrar** [comment]
You can use $infoRequest->setPassword('xxxxxxx'); to set auth info for the request.

**Comment by karborator** [comment]
Fatal error: Uncaught Error: Call to undefined method Metaregistrar\EPP\eppInfoContactRequest::setPassword() in

**Comment by metaregistrar** [comment]
You are right, the password should be set to eppContactHandle

I have added this to the code, since it was missing.

Correct call is now:
        $contact = new Metaregistrar\EPP\eppContactHandle($contactid);
        $contact->setPassword('foobar');
        $info = new Metaregistrar\EPP\eppInfoContactRequest($contact);
