### ISSUE TITLE
How to use extensions

### ISSUE THREAD

**Issue by rugambafri** [metaregistrar/php-epp-client#337]
$this->conn->setExtensions(["fee-1.0", "fee-0.23", "domain-ext-2.3", "ext-1.0"]);
This code return error ,I don't no why .
 "code": "Error 2004: Unsupported extension '0'",
    "file": "/mnt/storage/rugamba/public_html/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppResponses/eppResponse.php",
    "message": "Error 2004: Unsupported extension '0'"

**Comment by metaregistrar** [comment]
You cannot set multiple extensions with this call. Please do it one by one.

**Comment by luggesexe** [comment]
> I have an issue setting Extensions. I tried as described here setting only one Extension which led to the same error given. I fixed this by using "useExtension". This worked just fine but I keep getting a "not found" error on
> 
> `urn:ietf:params:xml:ns:[changePoll-1.0]` and `https://www.nic.ch/epp/balance-1.0`.
> 
> How can these two be implemented? It is not working with useExtension. Only secDNS-1.1 and rgp-1.0 are working.
> 
> Appreciate any help 👍

`$this->Verbindung->enableDnssec();
 $this->Verbindung->enableRgp();
 $this->Verbindung->addExtension("changePoll-1.0", "urn:ietf:params:xml:ns:changePoll-1.0");
 $this->Verbindung->addExtension("balance-1.0", "https://www.nic.ch/epp/balance-1.0");`

Above seems to work.
