### ISSUE TITLE
register domain 

### ISSUE THREAD

**Issue by karborator** [metaregistrar/php-epp-client#34]
Hi I got "Command failed" on register domain . 

Here is the xml request 

```
<?xml version="1.0" encoding="UTF-8"?>
<epp>
    <command>
        <create>
            <domain:create>
                <domain:name>some-demo.fi</domain:name>
                <domain:period unit="y">1</domain:period>
                <domain:registrant>*******</domain:registrant>
                <domain:authInfo>
                    <domain:pw>************</domain:pw>
        
                </domain:authInfo>
      
            </domain:create>
    
        </create>
        <clTRID>********</clTRID>
  
    </command>
</epp>
```

**Comment by metaregistrar** [comment]
HI,

I do not know why ficora would refuse the request, it looks fine.

Maybe they need an admin-c and tech-c address also, but you best ask ficora what the problem is.

**Comment by metaregistrar** [comment]
Hi,

I have a new request for connection to Ficora. Can you share the modifications you have made to connect to Ficora, so others can also benefit from this?

**Comment by karborator** [comment]
Hello , 

I think I did not  found a salutation for this issue :"Command failed" on register domain

**Comment by metaregistrar** [comment]
Hi,

That is good,

Can you share the changes you have made to make this connection work?

Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar

2016-05-17 12:58 GMT+02:00 karborator <notifications@github.com>:

**Comment by karborator** [comment]
$conn = new eppConnection(false);
        $conn->setHostname('epptest.ficora.fi');    
        $conn->setPort(700);                        
        $conn->setTimeout(200);                    
        $conn->setUsername('username'); //ask Ficora
        $conn->setPassword('password');        
        $realPathToPem = realpath(__DIR__ . '/path/to/ficora.pem'); 
        if (!$realPath) {
            throw new \Exception();
        }
        $conn->enableCertification($realPathToPem, 'password');

        if (!$conn->connect()) {
            throw new \Exception('Epp connection failed');
        }
        if (!$conn->login()) {
            throw new \Exception('Epp login failed');
        }
        return $conn;
