### ISSUE TITLE
Error when response XML contains '<'

### ISSUE THREAD

**Issue by davey013** [metaregistrar/php-epp-client#348]
I had an issue where the authorisation code of a domain contained a '<' . This results in error when it tries to read the response XML. 

I had to reset the authorisation code for the domain manually to get it back working again.

Example XML line:

`<domain:pw>rand0m<passw0rd</domain:pw>`

**Comment by metaregistrar** [comment]
Normally, the XML should contain CDATA structures to properly process strange characters in the XML. I have not checked if the password field contains this, but it should
