### ISSUE TITLE
cant get nicat connection working

### ISSUE THREAD

**Issue by arglbargl** [metaregistrar/php-epp-client#349]
So I am trying to get this client to run with nic.at epp.
The checkdomain example worked, but the createcontact does not - because it needs this special nicat version.

So I tried to start simple and used the alternativeconnection.php example and changed
`$conn = new Metaregistrar\EPP\metaregEppConnection();`
just to 
`$conn = new Metaregistrar\EPP\nicatEppConnection();`
However this gets the eroor:
`PHP Fatal error:  Uncaught Error: Class 'Metaregistrar\EPP\nicatEppConnection' not found in /root/php-epp-client/Examples/at_alternativeconnection.php:5`
Most likely I have to tell at_alternativeconnection.php somehow how to get the nicatEppConnection class or so?
Or do I have to copy the  ./Registries/nicatEppConnection/nicatEppConnection.php somewhere else?
And yes, you guessed it: my OOP skills in PHP are kinda limited ;)

**Comment by arglbargl** [comment]
Unfortunately no.
It is a pity, cause the package looks quite promising.
So, I am still using my old perl scripts instead.

**Comment by murat058** [comment]
Where are you from? could you share your code with me please? I've been at it for months but can't do it

**Comment by wninaus** [comment]
Hi!
Try to use 
`$conn = new Metaregistrar\EPP\atEppConnection();`
that worked for me
