### ISSUE TITLE
Unexpected closed connection by remote host

### ISSUE THREAD

**Issue by hackercoderprogrammer** [metaregistrar/php-epp-client#354]
Hello i try to connect to registry ,check the domain name availability,but i got this error
"ERROR: Unexpected closed connection by remote host... ==== LOG ==== -----Connection made-----2023-04-25 09:38:24----- Stream opened to tcp://mtanzania.tznic.or.tz port 700 -----END-----2023-04-25 09:38:24----- -----WRITE-----2023-04-25 09:38:24----- XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 1.0 en urn:ietf:params:xml:ns:domain-1.0 urn:ietf:params:xml:ns:contact-1.0 urn:ietf:params:xml:ns:host-1.0 64479f9076dc7 -----END-----2023-04-25 09:38:24-----"
Please help to resolve this.I try to double check it seems like i got connection but i can login.

**Comment by hammaadd** [comment]
You can change tcp:// to tls:// and test If it works or not I have faced the same error, And it got resolved by using tls://
