### ISSUE TITLE
EURid: Cancel a scheduled deletion

### ISSUE THREAD

**Issue by mvdgeijn** [metaregistrar/php-epp-client#357]
Hi,

I've search in the code, but I can't find a way to cancel a scheduled domain deletion. In the EURid doc's it states:

> If registrars execute a <domain:delete> command containing the element <domainext:cancel>, the existing deletion date will be cleared.

How can this be done using php-epp-client? Is it supported?

**Comment by metaregistrar** [comment]
This repository depends heavily on the contributions of external developers. If you need this extension to be recognized and processed, please add the code yourself and put it up in a pull request.
