### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by W0rma** [metaregistrar/php-epp-client#358]
We are using this package on PHP 8.1 and it is working fine.

However, we notice several PHP deprecation warnings:

```
Deprecated: Return type of Metaregistrar\EPP\eppResponse::saveXML(?DOMNode $node = null, $options = null) should either be compatible with DOMDocument::saveXML(?DOMNode $node = null, int $options = 0): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated
```

Are there any plans to tackle them?

Some month ago I created https://github.com/metaregistrar/php-epp-client/pull/346 which should fix the deprecation warnings at least in the classes/methods which are used by us.

**Comment by metaregistrar** [comment]
A pull request fixing the warnings was approved today, and will be baked into a new version soon
