### ISSUE TITLE
Get extended contact properties from SIDN contact

### ISSUE THREAD

**Issue by BusinessConnect** [metaregistrar/php-epp-client#362]
I've created some code to retrieve a contactperson from SIDN. It works but I don't see how to get the extended values for legalForm and legalFormNo.
I've added the SIDN-extension in my code:
`$conn->useExtension('sidn-ext-epp-1.0');
 $conn->useExtension('command-ext-1.0');
 $conn->useExtension('contact-ext-1.3');`

Further on we set this:
`$objHandleInfo = new Metaregistrar\EPP\eppInfoContactRequest(new eppContactHandle($strHandleID));
$Response = $conn->writeandread($objHandleInfo);`

We see the data in the returned XML (using saveXML) but how can we retrieve both values ?

**Comment by metaregistrar** [comment]
When using $conn->useExtension('sidn-ext-epp-1.0');, you have the ability to map the eppInfoContactResponse to an sidnEppInfoContactResponse. When mapped, you can use this object structure to retrieve the fields.
