### ISSUE TITLE
Adding our own extensions

### ISSUE THREAD

**Issue by DennisSkov** [metaregistrar/php-epp-client#363]
Hi.

We're trying to use this software to communicate with the Punktum DK (formerly known as DK Hostmaster) EPP service. Various commands require a custom extension. The domain:create command requires the `dkhm:orderconfirmationToken` in some cases.

How would we go about adding these custom extensions?

We've used composer to require this into our own project if that's relevant.

Edit:
I know how we can add custom extensions directly to the code. I just need to know how it can be done when using composer if that makes any sense.

**Comment by metaregistrar** [comment]
You will have to program it yourself in Protocols/EPP/eppExtensions. Please look at the other extensions in this directory to see how that works.
