### ISSUE TITLE
LIBXML_NOEMPTYTAG causing issues for some registries

### ISSUE THREAD

**Issue by DennisSkov** [metaregistrar/php-epp-client#366]
Hello.

Some registries does not allow empty tags.
When the `write` function is run, it's done with the option `LIBXML_NOEMPTYTAG`.

This means that 
```
<update>
      <domain:update xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
        <domain:name>example.com</domain:name>
        <domain:add/>
        <domain:rem/>
        <domain:chg/>
      </domain:update>
    </update>
```
becomes 
```
<update>
      <domain:update xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
        <domain:name>primaservers.dk</domain:name>
        <domain:add></domain:add>
        <domain:rem></domain:rem>
        <domain:chg></domain:chg>
      </domain:update>
    </update>
```
which is not allowed for some requests.

Could we have the option to overwrite setting the LIBXML_NOEMPTYTAG option?

**Comment by metaregistrar** [comment]
You can create your own branch with this change. I have not encountered registries so far that have a problem with this.
