### ISSUE TITLE
Client transaction id does not match returned

### ISSUE THREAD

**Issue by smitpatelvi** [metaregistrar/php-epp-client#367]
Metaregistrar\EPP\eppException: Client transaction id XXXXXXXXXXXXXXXXX does not match returned XXXXXXXXXXXXX in file vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 1001

i installed latest version of package.

name : metaregistrar/php-epp-client
descrip. : Object-oriented PHP EPP Client
keywords : domains, epp, xml
versions : * 1.0.12
Laravel Version : 9.52.15  
PHP Version :  8.1.24  
Composer Version :  2.2.5

i still got this error can you please help me to fix this?

@metaregistrar can please help me to fix this issue.

**Comment by metaregistrar** [comment]
Hello,

You are receiving this message when you receive an EPP result that does not match the request that you have put in.

So for example, if you put in an EPP request with number 1, but the request takes a long time to process. In the mean time you send a new request with number 2, but you receive an answer for request number 1. 
In that case you get this message.
