### ISSUE TITLE
Contact create missing tags legalForm and legalFormRegNo in request XML

### ISSUE THREAD

**Issue by veehof** [metaregistrar/php-epp-client#369]
I Try to add contact, error in response occurs with code A0001: The number of field/message component occurrences is incorrect. I hink this is regarding to missing tags legalForm and legalFormRegNo in request body. How can I add legalForm and legalFormRegNo to create an contact? I would expect these parameters at the function createcontact.

**Comment by micheldeking** [comment]
Same here:
<sidn-ext-epp:msg code="A0001" field="Legal form">The number of field/message component occurrences is incorrect (min=1, max=1)</sidn-ext-epp:msg>

**Comment by codenitrr** [comment]
Same issue, anyone?

**Comment by metaregistrar** [comment]
When creating a contact, use the object sidnEppCreateContactRequest (as opposed to eppCreateContactRequest).

The sidnEppCreateContactRequest object contains all the specific fields to create contacts with SIDN.
