### ISSUE TITLE
ERROR: Error writing content

### ISSUE THREAD

**Issue by hackercoderprogrammer** [metaregistrar/php-epp-client#370]
Hello,I got this error when i try to connect by using php-epp-client

ERROR: Error writing content ==== LOG ==== -----Connection made-----2023-11-11 14:37:25----- Stream opened to tls://... port 700 with protocol TLSv1.3, cipher TLS_AES_256_GCM_SHA384, 256 bits TLSv1.3 -----END-----2023-11-11 14:37:25----- -----WRITE-----2023-11-11 14:37:35----- XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 1.0 en urn:ietf:params:xml:ns:domain-1.0 urn:ietf:params:xml:ns:contact-1.0 urn:ietf:params:xml:ns:host-1.0 654f91af09717 -----END-----2023-11-11 14:37:35----- -----DISCONNECT-----2023-11-11 14:37:35----- Disconnected -----END-----2023-11-11 14:37:35-----

Please help.

**Comment by hackercoderprogrammer** [comment]
Hello,anyone with an ideal of this error message,please help.

**Comment by metaregistrar** [comment]
Please make sure you are whitelisted with the registry / registrar that you are connecting to. Please reach out to them to ask why the connection is not succesful.
