### ISSUE TITLE
No valid response class found for request class Metaregistrar\\EPP\\verisignEppDnssecUpdateDomainRequest

### ISSUE THREAD

**Issue by nashrull13** [metaregistrar/php-epp-client#371]
Hello,

i've been struggling with this. but still same result

my dnssec.php is just like this : 

use Metaregistrar\EPP\eppDomain;
use Metaregistrar\EPP\eppHost;
use Metaregistrar\EPP\eppSecdns;
use Metaregistrar\EPP\eppInfoDomainRequest;
use Metaregistrar\EPP\eppUpdateDomainRequest;
use Metaregistrar\EPP\eppDnssecUpdateDomainRequest;
use Metaregistrar\EPP\verisignEppInfoDomainRequest;
use Metaregistrar\EPP\verisignEppDnssecUpdateDomainRequest;

can anyone help?

**Comment by metaregistrar** [comment]
Please make sure that you do not create an 'eppConnection' object, but a verisignEppConnection object

Or, alternatively, make sure the Verisign extensions are loaded:
        parent::useExtension('verisign');
        $this->enableRgp();
        $this->enableDnssec();
