### ISSUE TITLE
New release with fixed PHP 8.2 deprecation warnings

### ISSUE THREAD

**Issue by W0rma** [metaregistrar/php-epp-client#374]
We are using [version 1.0.12](https://github.com/metaregistrar/php-epp-client/releases/tag/1.0.12) with PHP 8.2 which is fine in general.

However, we still notice the deprecation warning fixed by https://github.com/metaregistrar/php-epp-client/pull/365 because no new version containing this fix has been merged.

When can we expect a new version 1.0.13 of this package?

**Comment by W0rma** [comment]
> When can we expect a new version 1.0.13 of this package?

@metaregistrar Do you have any ETA for a new version? Please let me know if you need any help.

**Comment by W0rma** [comment]
@metaregistrar FYI We use this package in our PHP 8.3 app.

The only PHP warnings are the ones fixed in https://github.com/metaregistrar/php-epp-client/pull/365.

It would be great to have a tagged release containing these changes.

**Comment by metaregistrar** [comment]
A new release with tag 1.0.12 was baked today
