### ISSUE TITLE
[Enhancment] Provide support for NORID (.no)

### ISSUE THREAD

**Issue by Mycosis** [metaregistrar/php-epp-client#38]
As title says. I'd like to see support for the Norwegian registrar NORID for .no domains.
https://www.norid.no/en/registrar/system/tjenester/epp-webclient/

**Comment by metaregistrar** [comment]
Hello Mycosis,

Since we ourselved have no connection to Norid, i cannot create the code for you. I can help you to make it, however, and would really appreciate it if it is added to the repository as a pull request when it works.
