### ISSUE TITLE
Verisign Premium Domain Check Request

### ISSUE THREAD

**Issue by khelaia** [metaregistrar/php-epp-client#384]
I am using :
```php
$conn->useExtension('charge-1.0');
```

for another registry works perfectly but for verisign I am getting error:

Call to undefined method Metaregistrar\\EPP\\eppCheckDomainResponse::getChargeForDomainName()

I think Verisign have premium domain support and why does not work this extention?

**Comment by metaregistrar** [comment]
You are using eppCheckDomainResponse, but you should be using chargeEppCheckDomainResponse.
This class contains the addition "getChargeForDomainName()", where eppCheckDomainResponse does not have it.

**Comment by khelaia** [comment]
how can I use?
```

        if ($this->isVerisign) {
            $check = new verisignEppCheckDomainRequest($domains);
        } else {
            $check = new eppCheckDomainRequest($domains);
        }
        if ($response = $this->conn->request($check)) {
            $checkedDomains = $response->getCheckedDomains();
            $result = [];
            foreach ($checkedDomains as $checkedDomain) {
                $name = $checkedDomain['domainname'];
                /* @var $response \Metaregistrar\EPP\chargeEppCheckDomainResponse */
                $charges = $response->getChargeForDomainName($name);
            }
```
