### ISSUE TITLE
Domain contacts update problems

### ISSUE THREAD

**Issue by AkaeyesWanabe** [metaregistrar/php-epp-client#385]
I try epp client API for interact with cocca server.
Domain is created successfully with all contacts and name servers.
When we try to update contact:
1- registrant contacts is never update
`
    $response = null;
    try {
        // First, retrieve the current domain info. Nameservers can be unset and then set again.
        $domain = new eppDomain($domainName);
        $info = new eppInfoDomainRequest($domain);
        if ($response = $conn->request($info)) {
            $mod = new eppDomain($domainName);
            $d = $response->getDomain();
            //
            foreach ($d->getContacts() as $contact) {
                switch ($contact->getContactType()) {
                    case eppContactHandle::CONTACT_TYPE_REGISTRANT:
                        if ($registrant) {
                            $update = new eppContact(new eppContactPostalInfo($registrant["fullName"], $registrant["city"], $registrant["countryCode"], $registrant["organisation"], $registrant["address"], null, $registrant["postcode"], eppContact::TYPE_LOC), $registrant["email"], $registrant["phone"]);
                            $up = new eppUpdateContactRequest($contact, null, null, $update);
                            if (!$conn->request($up)) {
                                return ["success" => false, "data" => "Registrant contacts error"];
                            }
                        }
                        break;
                    default:
                }
            }
            //
            $update = new eppUpdateDomainRequest($domain, null, null, $mod);
            if ($response = $conn->request($update)) {
                return ["success" => true];
            }
        }
    } catch (eppException $e) {
        if ($response instanceof eppUpdateDomainResponse) {
            return ["success" => false, "data" => $response->textContent];
        }
    }
`

2- for all another contacts, the name is replace by the email.  for example admin contacts

`
case eppContactHandle::CONTACT_TYPE_ADMIN:
                        if ($adminContact) {
                            $update = new eppContact(new eppContactPostalInfo($adminContact["fullName"], $adminContact["city"], $adminContact["countryCode"], $adminContact["organisation"], $adminContact["address"], null, $adminContact["postcode"], eppContact::TYPE_LOC), $adminContact["email"], $adminContact["phone"]);
                            $up = new eppUpdateContactRequest($contact, null, null, $update);
                            if (!$conn->request($up)) {
                                return ["success" => false, "data" => "Admin contacts error"];
                            }
                        }
                        break;
`

Please could you help us ? we need help quickly for an existing project. I thank you for you works.

**Comment by metaregistrar** [comment]
It depends on what the registry gives back as error message. Most of the registries do not permit you to update contact name or contact company name, when a contact handle is associated with a domain name. 

That might be the problem in this case, but without the registry error message we will never know.

**Comment by AkaeyesWanabe** [comment]
Okay thank you for you answer.
