### ISSUE TITLE
Cannot declare class Metaregistrar\EPP\euridEppInfoDomainResponse, because the name is already in use 

### ISSUE THREAD

**Issue by sayoki** [metaregistrar/php-epp-client#389]
Cannot declare class Metaregistrar\EPP\euridEppInfoDomainResponse, because the name is already in use 

/Protocols/EPP/eppExtensions/domain-ext-2.5/eppResponses/euridEppInfoDomainResponse.php [line] => 0 )

**Comment by metaregistrar** [comment]
When you use parent::useExtension('domain-ext-2.5');

the classes will automatically be imported and you do not have to declare them any more.
