### ISSUE TITLE
Use PHP7

### ISSUE THREAD

**Issue by ramb0Ram** [metaregistrar/php-epp-client#39]
Hi.
¿This library is compatible with PHP 7 ?
Thanks

**Comment by metaregistrar** [comment]
Hi Alberto,

Some users have tried it and found problems with DomDocument and PHP7.

I will test and fix those issues soon.

**Comment by metaregistrar** [comment]
Hello Alberto,

The latest DEV version of php-epp-client works fine with PHP 7. And also PHP 5.6

**Comment by ramb0Ram** [comment]
Thank you very very much.
