### ISSUE TITLE
modifydomain.php is bugged

### ISSUE THREAD

**Issue by TeekieWebHostingSA** [metaregistrar/php-epp-client#392]
modifydomain.php is bugged as it doesn't do any modifications in the NORID Registry, it says: "Command completed successfully;", but in the WHOIS and EPP Client, no changes has really been made to the domain name.

**Comment by metaregistrar** [comment]
The code in modifydomain.php is only meant as Example code, to get a developer started. It is by no means designed to make actual changes.
