### ISSUE TITLE
How to cancel a pending action?

### ISSUE THREAD

**Issue by swartjie** [metaregistrar/php-epp-client#396]
Hey Guys,

How does one go about cancelling a pending update, or a pending domain deletion?
I've checked the examples and the doc's not been able to find a solution in the given resources...

Any advise would be awesome?

**Comment by metaregistrar** [comment]
Other than cancelling a pending transfer request, there are no EPP commands to cancel a pending delete or a pending change. It might be that some registry has implemented this, but it is by no means standard EPP.

**Comment by swartjie** [comment]
Hey @metaregistrar I do suspect it's something custom to the co.za registry, as I have an example command, but no documentation.

How can I run a spesific xml?
That way I can structure the xml to be able to run the cancel command :)

**Comment by metaregistrar** [comment]
When a registry adds specific commands to do specific tasks in EPP, they will create epp extensions. Addon commands to the standard EPP command set.

Please look in the directory Protcols/EPP/eppExtensions to see how extensions from other registries are used and processed. There may be even someone else that has already implemented the specific extensions from CO.ZA

**Comment by swartjie** [comment]
I saw this: https://www.registry.net.za/content.php?wiki=1&contentid=18&title=EPP%20Contact%20Extensions

How would I go about adding the cancel pending update request into the class?
