### ISSUE TITLE
domain info dns.be

### ISSUE THREAD

**Issue by pc-partner** [metaregistrar/php-epp-client#40]
Hi,
While checking if domainname is valid is working.
Domaininfo is returning nothing: "Retrieving info on xxxx.be " with no further details.

**Comment by metaregistrar** [comment]
Hi,

Have you tried enabling logging / debugging?

$conn = eppConnection::create('path-to-ini-file',true);

This enables the log and you can see what is happening exactly

**Comment by pc-partner** [comment]
Yes, Got the error: “Object does not exist xxxx.be”  so that domein doesn’t exist in tryout.
Maybe also show this error?
 
Van: Ewout de Graaf [mailto:notifications@github.com] 
Verzonden: donderdag 16 juni 2016 11:40
Aan: metaregistrar/php-epp-client <php-epp-client@noreply.github.com>
CC: pc-partner <tom@pc-partner.be>; Author <author@noreply.github.com>
Onderwerp: Re: [metaregistrar/php-epp-client] domain info dns.be (#40)
 
Hi,
Have you tried enabling logging / debugging?
$conn = eppConnection::create('path-to-ini-file',true);
This enables the log and you can see what is happening exactly

**Comment by pc-partner** [comment]
And if you try checking for an existing domain BUT is isn't on you account you got authentication error.

**Comment by metaregistrar** [comment]
That is correct: domain:check can be done on any domain name, but domain:info only on your own domain names. 

Except when you have a correct authentication code (transfer code) for the domain name, then you can do domain:info with transfer code and get the info

About showing the error: If you make sure that you catch the eppException, you can show the error.
