### ISSUE TITLE
Support for custom response logging

### ISSUE THREAD

**Issue by aksl** [metaregistrar/php-epp-client#49]
As the title says, would be nice to be able to add a custom logger for written and read responses. Prerably with an access to Request and Response objects, so in writeandread() -method after the default READ log write. I can do some work on this, just need to decide how it gets implemented (event listener, callback or what).

**Comment by metaregistrar** [comment]
Sounds like a great idea. I always wanted to make a better logging for EPP events, but never got round to doing it.

**Comment by aksl** [comment]
Made an initial approach to this in https://github.com/aksl/php-epp-client/tree/logging. Thoughts? The plan is to add a eppLogger that passes the log events to Psr\Log\LoggerInterface compliant logger.

**Comment by aksl** [comment]
@metaregistrar any thoughts on the approach?

**Comment by metaregistrar** [comment]
Hi Aksl,

I would keep the logging class out of the EPP directory. The logging is not strictly related to EPP, and if it is a basic class it can also be used for TMCH logging, for example. So you can either create a directory for that, or add the classes at the root level. Maybe it is best also not to use the Metaregistrar/EPP namespace but create a separate Metaregistrar/Log or Metaregistrar/Logging namespace for that.
