### ISSUE TITLE
Minimum required version of PHP is invalid

### ISSUE THREAD

**Issue by aksl** [metaregistrar/php-epp-client#50]
The array shorthand ([]) syntax is being used at eppInfoContactResponse->getContactPostalInfo() (`$postalinfo = [];`) and also multiple times at eppHelloResponse for example.

Given [it was introduced in PHP 5.4](http://php.net/manual/en/migration54.new-features.php), maybe update the minimum version requirement to PHP 5.4.

**Comment by metaregistrar** [comment]
Done ;-)
