### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by Olvikolvi** [metaregistrar/php-epp-client#58]
ficoraEppInfoContactResponse:
missing getRegisternumber (contact:registernumber) and getIdentifynro (contact:identity)

**Comment by aksl** [comment]
According to the [XML-schemas](https://www.viestintavirasto.fi/attachments/Schemas.zip) and personal testing, Ficora does not return those fields.

Can you verify that you can get them with the contact info response? Easiest way test is to make a contact info request with logging enabled, which will output every request and response sent.

I'm happy to implement those methods if the corresponding fields are present in the responses.

**Comment by Olvikolvi** [comment]
Yes I'am sure.. If type is company you will get registernumber and if person you get identity. Like you only get firstname and lastname if type is person.
Here are exsamples: http://pastebin.com/EGmPGxzE
