### ISSUE TITLE
Command syntax error in ficora

### ISSUE THREAD

**Issue by mazanax** [metaregistrar/php-epp-client#62]
I'm trying to get info of domain registered thru ficora but it returns syntax error. What I'm doing wrong?

```
        $info = new eppInfoDomainRequest(new eppDomain($domain));
        if ($response = $this->conn->request($info)) { // throws exception with syntax error
            /** @var \Metaregistrar\EPP\eppInfoDomainResponse $response */
            $data = $response->getDomain();
            foreach ($data->getContacts() as $contact) {
                /** @var eppContactHandle $contact */
                echo $contact->getContactType() . ': ' . $contact->getContactHandle() . PHP_EOL;
            }
        }
```

$this->conn:
```
        $conn = new \Metaregistrar\EPP\ficoraEppConnection();
        $conn->setHostname($host);
        $conn->setPort($port);
        $conn->setUsername($username);
        $conn->setPassword($password);

        if (null === $conn) {
            throw new RuntimeException('Cannot create connect to ficora');
        }
        $conn->enableCertification($key, $keyPassword, false);
        $this->conn = $conn;
        $this->conn->login();
```

**Comment by vincentdecarpigny** [comment]
Hi Alexander,

as far as I know you cannot use the eppInfoDomainRequest directly, you need
to extend it like this :

<?php
namespace Metaregistrar\EPP;

class ficoraEppInfoDomainRequest extends eppInfoDomainRequest {

/*

<?xml version="1.0" encoding="UTF-8"?>
<epp>
<command>
<info>
<domain:info xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
<domain:name>mydummydomainname.fi</domain:name>
<domain:authInfo>
<domain:pw/>
</domain:authInfo>
<contact:authInfo>
<contact:pw>LoloL</contact:pw>
</contact:authInfo>
</domain:info>
</info>
<clTRID>5809c755b90a5</clTRID>
</command>
</epp>


*/

function __construct($infodomain, $hosts = null, $namespacesinroot = true){
parent::__construct($infodomain, $hosts = null, $namespacesinroot = true);
$this->addFICORAExtension();
$this->addSessionId();
//tprint(htmlentities($this->saveXML()));
}

public function addFICORAExtension(){
$this->domainobject->setAttribute('xmlns:domain','urn:ietf:params:xml:ns:domain-1.0');
}
}

Best,
Vincent

2016-11-29 15:05 GMT+01:00 Alexander <notifications@github.com>:

**Comment by aksl** [comment]
It would be enough to just use false parameter for $namespacesinroot argument of the request constructor. This applies atleast to the following classes when communicating with Ficora:
- eppInfoContactRequest
- eppCheckContactRequest
- eppInfoDomainRequest
- eppCreateDomainRequest
- ficoraEppUpdateDomainRequest (false by default)
- eppCheckDomainRequest
- eppRenewRequest

Example request with namespacesinroot set to false:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1" xmlns:ficora="http://www.ficora.fi/epp/ficora">
  <command>
    <info>
      <domain:info xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
        <domain:name hosts="all">DOMAIN</domain:name>
        <domain:authInfo>
          <domain:pw></domain:pw>
        </domain:authInfo>
      </domain:info>
    </info>
    <clTRID>....</clTRID>
  </command>
</epp>
```

As you can see from eppDomainRequest, setting it to false does exactly the same as adding a special method for it:
```php
if (!$this->rootNamespaces()) {
    $this->domainobject->setAttribute('xmlns:domain','urn:ietf:params:xml:ns:domain-1.0');
}
```
Removing the addFicoraExtension() -method and replacing it with different default value for $namespacesinroot might be a lighter approach.
