### ISSUE TITLE
where to put domain to check ?

### ISSUE THREAD

**Issue by cr0co** [metaregistrar/php-epp-client#69]
Hello

Im new in this, where i have to put the domain names to check for infodomain, checkdomain, registerdomain etc.. ?

Greetings and thanks for Help !
Remo

**Comment by metaregistrar** [comment]
Hello Remo,

Please review the file Examples/checkdomain.php, it is a complete example
script of how to use the checkdomain command.

Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar

2016-12-16 20:29 GMT+01:00 cr0co <notifications@github.com>:

**Comment by cr0co** [comment]
hey thats the first thing i did.
There is no domain in it, can you give me a hint pls ?

**Comment by metaregistrar** [comment]
The domain name is a parameter to checkdomain.php

It is in the code:
if ($argc <= 1) {
echo "Usage: checkdomain.php <domainnames>\n";
echo "Please enter one or more domain names to check\n\n";
die();
}

Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar

2016-12-16 22:19 GMT+01:00 cr0co <notifications@github.com>:

**Comment by cr0co** [comment]
thanks for you help

so i have to make a form, for the domainname input, and pass it do checkdomain.php ?
with the $argc parameter

**Comment by metaregistrar** [comment]
No, this software is made to run in a command-line environment, not on a web interface.

So what you would do is open a command interpreter and type:
php checkdomain.php domainname-to-check.extension-to-check

**Comment by cr0co** [comment]
oh, i think its a web interface, sorry for my questions
