### ISSUE TITLE
ERROR: Unexpected closed connection by remote host...

### ISSUE THREAD

**Issue by ankandc** [metaregistrar/php-epp-client#71]
I want to register .nl domains with SIDN using this metaregistrar project.Now, after creating settings.ini, checkdomain.php should be working as mentioned in the documentation. But, after creating settings.ini I am trying to run checkdomain.php independently by providing domain name statically inside checkdomain.php, however, when I run it in the browser from localhost, each time it is showing an error (ERROR: Unexpected closed connection by remote host...). Also, inside settings.ini I have provided interface=eppConnection, hostname=ssl://epp.test2.metaregistrar.com and port=7443 as provided in the documentation of the project and as userid and password I am using the login credentials of https://drs.domain-registry.nl. Can you please tell me what the problem is? Do I need to change anything?

**Comment by webdevvie** [comment]
Hi @ankandc You are using your SIDN credentials to connect to Metaregistrar's servers. epp.test2.metaregistrar.com is the hostname of a test epp server for metaregistrar , not SIDN. 
So that isn't going to work. The Metaregistrar EPP server is rejecting your connection because your login credentials are invalid for their test server.

Please connect to the information you were provided by SIDN if you want to implement this using your own SIDN logins. Which you can certainly do with this project.

However Metaregistrar is a company that specialises in providing a single gateway to register and maintain different TLDs for their customers. You might consider giving them a go https://www.metaregistrar.com/ 

***full disclosure*** I work there :)

**Comment by metaregistrar** [comment]
Please make sure when logging in to the SIDN EPP servers, that your IP addresses are whitelisted with SIDN. Otherwise you will experience the disconnects you mentioned.

**Comment by ankandc** [comment]
hi @metaregistrar we have signed up for a metaregistrar account but we have not been contacted yet. Is there any problem? or will it take longer to contact us? Since, we have to start using your project as soon as possible due to our deadline, therefore it would be helpful if you would help us in any way or provide any suggestions.

**Comment by metaregistrar** [comment]
Hello Ankan,

I have 2 submissions for Ankan Mondal, but both of them seem to miss the correct address data. I will ask our people to contact you via e-mail about these requests.

**Comment by ankandc** [comment]
They gave me the credentials but unfortunately they gave the password wrong and suggested me to reset my password. Till now we have attempted twice to reset my password but we have received no mails from metaregistrar. Since as we told you earlier that we have to do it earliest possible, so please see if you can help in any way.

**Comment by metaregistrar** [comment]
Changed your EPP password and sent you a mail about it.

**Comment by ankandc** [comment]
Thank you for your efforts, however logging with the new password also
didn't work for me. I would request you to first test at your end and then
forward the same to me. Else also let me know if there is anything wrong
from my end. I have tried to log in to https://eppltest1.metaregistrar.com
with username (duc_ancan) and new password (c1UKqrSO8twi).

Thanks in advance
Regards
Ankan Mondal

**Comment by metaregistrar** [comment]
I noticed that you have not whitelisted your ip address. Please login, to to EPP users and whitelist the IP address you are connecting from.

**Comment by ankandc** [comment]
Our IP is white listed in SIDN and I am trying to log in to your website.
Do I need to whitelist my IP somewhere else also? If so, please guide us
and provide the url. It will be very grateful.

Thanks in advance
Regards
Ankan Mondal

**Comment by ankandc** [comment]
As we have told earlier, we want to register domains using your project. In
the last mail you told us about logging in and whitelisting our IP address
with EPP users in order to sign in to your site. Since we are not much
familiar with EPP and SIDN, therefore regarding that we need a little
guidance if possible. Please kindly specify the url of epp site where we
need to whitelist our IP so that we can proceed towards registering domains
with you.

Thanks in advance

Regards

Ankan Mondal
