### ISSUE TITLE
Example Auth request

### ISSUE THREAD

**Issue by pc-partner** [metaregistrar/php-epp-client#74]
Hi,

Has anywone an example on how to request a transfer key?
Implement EppAuthcodeRequest

**Comment by metaregistrar** [comment]
Most registries will give you the auth key in the domain:info command. Or you can set it with a domain:update command.

But some registries (.NU .BE for example) will not show the auth info in the domain:info command. These registries all have their own methods to retrieve the auth info, you should ask them. There is no uniform way.

**Comment by pc-partner** [comment]
You have at dnsbe the request: dnsbeEppAuthcodeRequest
That should be used. but how should it be used?

**Comment by metaregistrar** [comment]
If you have a direct connection to DNS Belgium, you can try:
$domainname = 'xxxxxxxx.be';
$request = new dnsbeEppAuthcodeRequest($domainname);
if ($response = $conn->request($request)) {
    echo $response->saveXML();
}

**Comment by pc-partner** [comment]
That works
