### ISSUE TITLE
possible to add .ch ? 

### ISSUE THREAD

**Issue by shuxx** [metaregistrar/php-epp-client#75]
https://www.nic.ch/export/shared/.content/files/EPP-Manual_en.pdf 
How to create our own configuration to add registrar ?

**Comment by metaregistrar** [comment]
Hello Shuxx,

If you want to add a registrar, download the code, add the registrar, and create a pull request. We will then incorporate your added code into our repository.

**Comment by webkp** [comment]
Hello @shuxx
sorry for hijacking this issue but have you been able to connect the client to nic.ch? 
I saw you opened several issues about that here and was wondering how it went in the end? Would you be able to share your example files?

**Comment by shuxx** [comment]
hey
no the project was abandoned.

**Comment by webkp** [comment]
thank you for your reply @shuxx. abandoned because you never got it up and running (so it's not working with nic.ch) or for other reasons? just so I know if it is worth testing

**Comment by shuxx** [comment]
My customer was not able to pay the invoice ... I was freelancer
