### ISSUE TITLE
No valid response class found for request class Metaregistrar\EPP\dnsbeEppTransferRequest

### ISSUE THREAD

**Issue by pc-partner** [metaregistrar/php-epp-client#76]
When trying to do a transfer like this:
 try {
            $domain = new eppDomain($domainname);
            $domain->setAuthorisationCode($authcode);
            $transfer = new dnsbeEppTransferRequest(dnsbeEppTransferRequest::OPERATION_REQUEST, $domain);
            if ($response = $conn->request($transfer)) {
                /* @var $response Metaregistrar\EPP\eppTransferResponse */
                echo $response->getDomainName(), " transfer request was succesful\n";
                return true;
            }
        } catch (eppException $e) {
            echo $e->getMessage() . "\n";
            return $e->getMessage() . "\n";
        }

I get the error:
No valid response class found for request class Metaregistrar\EPP\dnsbeEppTransferRequest

**Comment by pc-partner** [comment]
Any news?

**Comment by metaregistrar** [comment]
In the file Registries/dnsbeEppConnection/eppConnection.php there should be a line stating:

parent::addCommandResponse('Metaregistrar\EPP\dnsbeEppTransferRequest', 'Metaregistrar\EPP\eppTransferResponse');

This creates a connection to the response class for Metaregistrar\EPP\dnsbeEppTransferRequest

**Comment by pc-partner** [comment]
Correct. I had old version!
