### ISSUE TITLE
still have error

### ISSUE THREAD

**Issue by shuxx** [metaregistrar/php-epp-client#78]
Failed to enable crypto, i verifed ssl & nmap to the epp server...
A idea ?

**Comment by metaregistrar** [comment]
which hostname do you use for your connection?

**Comment by shuxx** [comment]
tls://epp-test.switch.ch

**Comment by metaregistrar** [comment]
Can you try ssl://epp-test.switch.ch? Or without ssl://, just epp-test.switch.ch?

**Comment by shuxx** [comment]
Without : php checkdomain.php sinmedia.ch
Checking 1 domain names
ERROR: Unexpected closed connection by remote host...

with ssl:// : php checkdomain.php sinmedia.ch
Checking 1 domain names
PHP Warning:  stream_socket_client(): Failed to enable crypto in /home/vagrant/Code/epp-client/Protocols/EPP/eppConnection.php on line 380

Warning: stream_socket_client(): Failed to enable crypto in /home/vagrant/Code/epp-client/Protocols/EPP/eppConnection.php on line 380
PHP Warning:  stream_socket_client(): unable to connect to ssl://epp-test.switch.ch:7001 (Unknown error) in /home/vagrant/Code/epp-client/Protocols/EPP/eppConnection.php on line 380

Warning: stream_socket_client(): unable to connect to ssl://epp-test.switch.ch:7001 (Unknown error) in /home/vagrant/Code/epp-client/Protocols/EPP/eppConnection.php on line 380

**Comment by metaregistrar** [comment]
Is it possible that switch.ch uses certificates for this connection, and that you need to upload your certificate first before connecting?

**Comment by metaregistrar** [comment]
You can try connecting with openssl via this command:
openssl s_client -connect epp-test.switch.ch:7001

If this succeeds, you should also be able to connect with php-epp-client

if this does not succeed, please ask switch.ch why it does not succeed and ask them for the correct way to connect

**Comment by shuxx** [comment]
Here the result from the prod server 
```
 openssl s_client -connect epp-test.switch.ch:7001
CONNECTED(00000003)
140091034675104:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:184:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 247 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

Here the result from Laravel/homestead vm : 
```
openssl s_client -connect epp-test.switch.ch:7001
CONNECTED(000001D0)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 308 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1486383666
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
6812:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
```

Switch as been contacted...

**Comment by shuxx** [comment]
ok, we all right, except switch who whitelist the wrong ip -_-" dumbass \o/

**Comment by Shubham4th** [comment]
I tied to hit via postman checkdomain.php showing that type error my post man url is "https://epp.thesst.com/epp/epp/checkdomain.php" 
can you help me ? I tried a lot but unable to resolve that type of error .

This is my settings.ini file below :

interface=eppConnection
hostname=epp.thesst.com
port=700
userid=xxxxxxx
password=xxxxxx
certificatefile=/home/admin/web/epp.thesst.com/public_html/epp/epp/ssl_cert/epp.thesst.com.crt


PHP Warning:  stream_socket_client(): Unable to set private key file `/home/admin/web/epp.thesst.com/public_html/epp/epp/ssl_cert/epp.thesst.com.crt' in /home/admin/web/epp.thesst.com/public_html/epp/epp/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 376
PHP Warning:  stream_socket_client(): Failed to enable crypto in /home/admin/web/epp.thesst.com/public_html/epp/epp/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 376
PHP Warning:  stream_socket_client(): unable to connect to ssl://epp.thesst.com:700 (Unknown error) in /home/admin/web/epp.thesst.com/public_html/epp/epp/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 376
ERROR: Error connecting to ssl://epp.thesst.com:700:  (code 0)

**Comment by Shubham4th** [comment]
> I tied to hit via postman checkdomain.php showing that type error my post man url is "https://epp.thesst.com/epp/epp/checkdomain.php"
> can you help me ? I tried a lot but unable to resolve that type of error .
> 
> This is my settings.ini file below :
> 
> interface=eppConnection
> hostname=epp.thesst.com
> port=700
> userid=xxxxxxx
> password=xxxxxx
> certificatefile=/home/admin/web/epp.thesst.com/public_html/epp/epp/ssl_cert/epp.thesst.com.crt
> 
> PHP Warning: stream_socket_client(): Unable to set private key file `/home/admin/web/epp.thesst.com/public_html/epp/epp/ssl_cert/epp.thesst.com.crt' in /home/admin/web/epp.thesst.com/public_html/epp/epp/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 376
> PHP Warning: stream_socket_client(): Failed to enable crypto in /home/admin/web/epp.thesst.com/public_html/epp/epp/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 376
> PHP Warning: stream_socket_client(): unable to connect to ssl://epp.thesst.com:700 (Unknown error) in /home/admin/web/epp.thesst.com/public_html/epp/epp/vendor/metaregistrar/php-epp-client/Protocols/EPP/eppConnection.php on line 376
> ERROR: Error connecting to ssl://epp.thesst.com:700: (code 0)

waiting for your response

**Comment by shuxx** [comment]
this issue IS NOT a support. if u want to have quick response or a working code just pay a developer. Thanks
