### ISSUE TITLE
Check for Domain Transfer/Lock Status

### ISSUE THREAD

**Issue by pc-partner** [metaregistrar/php-epp-client#81]
[DNSBE]
How can we check if a domain is possible to transfer?  (transferlock)
Seems that there is also a difference when you are the owner of the domain or not.

**Comment by metaregistrar** [comment]
Most registries will allow you to do domain:info if you have a valid AuthCode for the domain name, even if it is not in your portfolio.

but i do not know if DNS Belgium allows this.

**Comment by pc-partner** [comment]
Doesn't seems to be :(
