### ISSUE TITLE
Example - canceldomain.php

### ISSUE THREAD

**Issue by pc-partner** [metaregistrar/php-epp-client#83]
Is there another Example of canceldomain.php? Seems empty :)

**Comment by metaregistrar** [comment]
$epp = new Metaregistrar\EPP\eppDomain($domainname);
        $del = new Metaregistrar\EPP\eppDeleteRequest($epp);
        if ($response = $conn->request($del)) {
            echo "$domainname cancelled\n";
            return true;
        }
        else {
            return false;
        }

**Comment by pc-partner** [comment]
Thanks DBSNE also excepts <dnsbe:deleteDate>2010-10-10T10:10:10.0Z</dnsbe:deleteDate>.
Don't know if other registrar excepts this parameter.

**Comment by metaregistrar** [comment]
Example added
