### ISSUE TITLE
dnsbe createdomain- 2102: Unimplemented option

### ISSUE THREAD

**Issue by pc-partner** [metaregistrar/php-epp-client#85]
When trying to register you domain:

> $this->createdomain($conn, $domain, $contactid, $contactid, $contactid, $contactid, $nameservers);
You have the same problem when changing nameservers: Error 2102: Unimplemented option
Is there an eample on how to add  Host Attributes instead of Host Objects?

**Comment by metaregistrar** [comment]
The second parameter of the eppCreateDomainRequest is $forceHostAttr

So to force host attributes, use this parameter as follows:
$domain = new eppDomain();
$create = new eppCreateDomainRequest($domain, true);
