### ISSUE TITLE
Unexpected closed connection by remote host...

### ISSUE THREAD

**Issue by ankandc** [metaregistrar/php-epp-client#86]
When we are trying to check domains through terminal using checkdomain.php it is generating an error "unexpected closed connection by remote host...". We have placed settings.ini file inside Examples folder.
Further we have provided,
 interface=eppConnection
hostname=ssl://epp.test2.metaregistrar.com
port=7443
and userid, password (provided by you)
in the settings.ini file. Please guide if we are doing anything wrong. Screenshot is attached.
![screenshot from 2017-02-16 15 27 33](https://cloud.githubusercontent.com/assets/25167089/23017612/fbea702a-f460-11e6-9c4b-647e474bb28e.png)

**Comment by metaregistrar** [comment]
You are using an old, obsolete test service that we will decommision shortly.

Please use ssl://eppltest1.metaregistrar.com port 7000 for your tests.
