### ISSUE TITLE
Authentication error 2200

### ISSUE THREAD

**Issue by ankandc** [metaregistrar/php-epp-client#87]
Now, while checking domain, it is showing the error "ERROR: Error 2200: Authentication error". This time hostname and port has been changed to: 
hostname=ssl://eppltest1.metaregistrar.com
port=7000
Please tell us about the authentication error, where do we need to authenticate. Screenshot is attached.
![screenshot from 2017-02-16 18 01 14](https://cloud.githubusercontent.com/assets/25167089/23021856/15a67b86-f474-11e6-9f7a-b0220707e564.png)

**Comment by ankandc** [comment]
We think that there is a little problem. We have already white listed our IP address in SIDN. It would be very helpful if you could tell us about the problem or the places where we need to be authenticated to use your API successfully.

**Comment by metaregistrar** [comment]
Hello,

Do you have a login for our test website? https://eppltest1.metaregistrar.com/

You can only use our EPP service when you already have login to our systems.

whitelisting your IP address with SIDN has no use in this case, since you are not connecting to SIDN but to our services.

**Comment by ankandc** [comment]
Yes we do have a login for your test website https://eppltest1.metaregistrar.com/, our username is duc-ankan.

**Comment by metaregistrar** [comment]
If you login to the site, on the menu left you have a menu item 'EPP' and 'Users'

There you see a username 'dualcube', you have to use this login.
i don't know the password, but you can reset the password if you want .

**Comment by ankandc** [comment]
Thanks for the help, but since we are a registrar at SIDN so we are trying
to connect to SIDN server using your API. We have modified your code a bit,
we have created the connection as:

$conn = sidnEppConnection::create(__ROOT__.'/settings.ini')

For that we have also included:

use Metaregistrar\EPP\sidnEppConnection;

and in settings.ini file we have provided:

interface=EppConnection
hostname=ssl://testdrs.domain-registry.nl
port=700
userid= (login credentials of testdrs.domain-registry.nl)
password=(login credentials of testdrs.domain-registry.nl)

That's it. Now, when we run the code we are getting error:

Checking 1 domain names ERROR: Error 2200: Authentication error

Can you please help?

Thanks in advance

Ankan Mondal

**Comment by metaregistrar** [comment]
Can you try it like this:

so it is eppConnection::create()

and in the interface settings.ini you specify sidnEppConnection

In this way you can use the same code for various registries.

$conn = eppConnection::create(__ROOT__.'/settings.ini')

use Metaregistrar\EPP\eppConnection;

and in settings.ini file we have provided:

interface=sidnEppConnection
hostname=ssl://testdrs.domain-registry.nl
port=700
userid= (login credentials of testdrs.domain-registry.nl)
password=(login credentials of testdrs.domain-registry.nl)

**Comment by ankandc** [comment]
We have got a new issue. Checking domains is now going smoothly. But while registering domains in https://eppltest1.metaregistrar.com we are getting an error "Error 2308: Validation of the transaction failed".
It would be very helpful for us if you could give us any idea regarding the error and also tell us if is it possible or not to check demo registering of domains using test account.

**Comment by metaregistrar** [comment]
Hi,

Which domain name are you trying to register? Not all extensions will work on the test interface.

**Comment by ankandc** [comment]
We are trying to test register bol.nl. And we are getting the following response "Registering bol.nl ns1.metaregistrar.nl exists ns2.metaregistrar.nl exists Error 2308: Validation of the transaction failed".

**Comment by ankandc** [comment]
We have tried to register "bol.nl" and the response being "Registering
bol.nl ns1.metaregistrar.nl exists ns2.metaregistrar.nl exists Error 2308:
Validation of the transaction failed". So, are we trying something invalid?
Can you provide any idea???
