### ISSUE TITLE
Remove dnssec key

### ISSUE THREAD

**Issue by universenl** [metaregistrar/php-epp-client#89]
Hi,

Inserting a new dnssec key works great, is there any api available for deleting a key also ?

Greatings

**Comment by metaregistrar** [comment]
new eppDnssecUpdateDomainRequest($add, $remove, $update)

Just put the keys to remove in the $remove object variable.

**Comment by universenl** [comment]
Can you give me an example of the remove object please, did try some things but not working.

Greatings.
