### ISSUE TITLE
Remove dnskey exemple

### ISSUE THREAD

**Issue by universenl** [metaregistrar/php-epp-client#91]
Hello,

After asking about remove a dnssec key from a registrar api, can i get a example of this remove object?

`new eppDnssecUpdateDomainRequest($add, $remove, $update)
Just put the keys to remove in the $remove object variable.`

Greatings

**Comment by metaregistrar** [comment]
For your convenience i have made an example script in Examples/removednssec.php to show how you remove dnssec keys.

First you get the current dnssec keys with domain:info, and then you remove them.

**Comment by universenl** [comment]
The example script gives a error:

Call to undefined function infodomain()

**Comment by universenl** [comment]
Nvm got it thanks!
