### ISSUE TITLE
eppException: Unexpected closed connection by remote host...

### ISSUE THREAD

**Issue by jvsplunder** [metaregistrar/php-epp-client#94]
```
$conn = new eppConnection();
$conn->setHostname('ssl://eppltest1.metaregistrar.com');
$conn->setPort(7000);
$conn->setUsername('');
$conn->setPassword('');
$conn->login();
```
I am using the following code, it throws an exception on the login function.
I tried using a username and password from metaregistrar epp users, but gave the same result as not using any password.

**Comment by metaregistrar** [comment]
Hello Jesse,

Can you try $conn->connect(); before $conn->login() to see if the connection works?

**Comment by jvsplunder** [comment]
Then it fails at $conn->connect();

**Comment by metaregistrar** [comment]
Hello Jesse,

I have tried to recreate your problem and found that you must not use ssl:// in case of the test services. 
I will modify the documentation on this point.

$conn = new eppConnection();
$conn->setHostname('eppltest1.metaregistrar.com');
$conn->setPort(7000);
$conn->setUsername('');
$conn->setPassword('');
$conn->login();

**Comment by jvsplunder** [comment]
I still have the problem, but this time it does check with username and password. so I guess I am using the wrong credentials?
Can I contact you for more support about the epp? I am a customer of metaregistrar.

**Comment by metaregistrar** [comment]
Please mail for support to support@metaregistrar.com
