### ISSUE TITLE
Get EURid Validdate authorisation code

### ISSUE THREAD

**Issue by jvdmb** [metaregistrar/php-epp-client#99]
We've added the following function in euridEppInfoDomainResponse.php:

    public function getAuthorisationCodeValidDate() {
        $xpath = $this->xPath();
        $result = $xpath->query('/epp:epp/epp:response/epp:extension/authInfo:infData/authInfo:validUntil');
        if ($result->length > 0) {
                return $result->item(0)->nodeValue;
        } else {
            return null;
        }
    }

Feel free to use it ;-)

**Comment by metaregistrar** [comment]
Added to the repository
